---
title: "site_70550"
format: html
editor: source
---

### Load Packages

```{r}

if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse, here, DBI, RPostgres, mgcv, lme4, lmerTest, plm)

```

### Connect to Database

```{r}
tryCatch({
    drv <- dbDriver("Postgres")
    print("Connecting to Database…")
    connection <- dbConnect(drv,
                 dbname = Sys.getenv("aws_dbname"),
                 host = Sys.getenv("aws_host"),
                 port = Sys.getenv("aws_port"),
                 user = Sys.getenv("aws_user"),
                 password = Sys.getenv("aws_password"),
                 timezone=NULL)
    print("Database Connected!")
    },
    error=function(cond) {
            print("Unable to connect to Database.")
    })

#search path
dbExecute(connection, "set search_path to survey_data")
```

### query data of interest

```{r}

# This query returns all organisms that are infected and have a SVL and body mass measurement 

q <- "select l.location, r.region, s.site, s.wilderness, v.date, s2.detection_type, c.species_capture, 
      c.svl_mm, c.body_mass_g, c.life_stage, qbr.target_quant_per_swab, qbr.detected, qbr.bd_swab_id 
      from location l 
      join region r on l.location_id = r.location_id 
      join site s on r.region_id = s.region_id 
      join visit v on s.site_id = v.site_id 
      join survey s2 on v.visit_id = s2.visit_id 
      join capture c on s2.survey_id = c.survey_id 
      join qpcr_bd_results qbr on c.bd_swab_id = qbr.bd_swab_id
      where c.svl_mm is not null
      and c.body_mass_g is not null
      and qbr.detected = '1';"

raw_data <- dbGetQuery(connection, q) 

```

### Wrangle Adult data - Site 70550

#### Initial wrangle

```{r}

# Here we filter only for adult RAMU, log10 +1 transform the bd load, and filter for adult life stage only. We then center and scale the variables. 

adult_data <- raw_data %>% 
  filter(species_capture == "rana_muscosa",
         life_stage == "adult") %>% 
  mutate(target_quant_per_swab = log10(target_quant_per_swab + 1)) %>%
  ungroup() %>% 
   mutate(body_mass_g = log(body_mass_g),
          svl_mm = log(svl_mm)) %>% 
   mutate(svl_mm = as.numeric(scale(svl_mm)),
          body_mass_g = as.numeric(scale(body_mass_g)),
          site = as.factor(site),
          wilderness = as.factor(wilderness))


# briefly examine how many sites we have available with greater then 100 observations. 

adult_site_count <- adult_data %>% 
  group_by(site) %>% 
  summarise(n = n()) %>% 
  filter(n > 100) %>% 
  select(site)


# Site 70550 data

final_adult_data <- adult_data %>% 
  filter(site == "70550")


```

### Models

#### Explore 
```{r}

# initial explore
hist(final_adult_data$svl_mm)

hist(final_adult_data$body_mass_g)

hist(final_adult_data$target_quant_per_swab)

cor(final_adult_data$svl_mm, final_adult_data$target_quant_per_swab)

cor(final_adult_data$body_mass_g, final_adult_data$target_quant_per_swab)
```

#### `lm()` to see sig and trend for adults at site 70550
```{r}
# svl_mm
adult_svl_mod <- lm(target_quant_per_swab ~ svl_mm , data = final_adult_data)

summary(adult_svl_mod)

# Seems longer frogs are less infected


# body_mass_g
adult_bm_mod <- lm(target_quant_per_swab ~ body_mass_g, data = final_adult_data)

summary(adult_bm_mod)

# Seems bigger frogs are less infected


# svl_mm * body_mass_g
adult_svl.bm_mod <- lm(target_quant_per_swab ~ svl_mm*body_mass_g, data = final_adult_data)

summary(adult_svl.bm_mod)

```

#### Visualize Adult `lm(target_quant_per_swab ~ svl_mm)`
```{r}

pred_svl_adult <- seq(min(final_adult_data$svl_mm), max(final_adult_data$svl_mm), len=100)

newdata_adult <- data.frame(svl_mm = pred_svl_adult)

mod_pred_adult = predict(adult_svl_mod, newdata = newdata_adult, se.fit = T, type = 'response')
newdata_adult$pred <- mod_pred_adult$fit
newdata_adult$upper_se <- mod_pred_adult$fit + (2 * mod_pred_adult$se.fit)
newdata_adult$lower_se <- mod_pred_adult$fit - (2 * mod_pred_adult$se.fit)

ggplot(newdata_adult) + 
  geom_point(data=final_adult_data, aes(x=svl_mm, y=target_quant_per_swab), size=0.5, alpha = 0.2) +
  geom_line(data=newdata_adult, aes(x=svl_mm, y=pred), linewidth = 1) +
  geom_ribbon(aes(ymin = lower_se, ymax= upper_se, x = svl_mm), alpha = 0.2, fill = "blue") +
  xlab("svl_mm") + ylab("Infection Intensity") + 
  theme_classic() +
  ggtitle(paste("Adult RAMU, Site 70550, Slope:", 
                round(summary(adult_svl_mod)$coefficients[2,1], 3), 
                ", p-value:", 
                round(summary(adult_svl_mod)$coefficients[2,4], 3), "*"))

```


### Wrangle SubAdult data - Site

#### Initial wrangle

```{r}
# Here we filter only for subadult RAMU, log10 +1 transform the bd load, and filter for adult life stage only. We then center and scale the variables. 
sub_data <- raw_data %>% 
  filter(species_capture == "rana_muscosa",
         life_stage == "subadult") %>% 
  mutate(target_quant_per_swab = log10(target_quant_per_swab + 1)) %>%
  ungroup() %>% 
   mutate(body_mass_g = log(body_mass_g),
          svl_mm = log(svl_mm)) %>% 
   mutate(svl_mm = as.numeric(scale(svl_mm)),
          body_mass_g = as.numeric(scale(body_mass_g)),
          site = as.factor(site),
          wilderness = as.factor(wilderness))


# briefly examine how many sites we have available with greater then 50 observations. 
sub_site_count <- sub_data %>% 
  group_by(site) %>% 
  summarise(n = n()) %>% 
  filter(n > 50) %>% 
  select(site)


# Site 70550 data
final_sub_data <- sub_data %>% 
  filter(site == "70550")


```

### Models

#### Explore Cor
```{r}

# initial explore 
hist(final_sub_data$svl_mm)

hist(final_sub_data$body_mass_g)

hist(final_sub_data$target_quant_per_swab)

cor(final_sub_data$svl_mm, final_sub_data$target_quant_per_swab)

cor(final_sub_data$body_mass_g, final_sub_data$target_quant_per_swab)
```

#### `lm()` to see sig and trend for subadults at site 70550
```{r}
# svl_mm
sub_svl_mod <- lm(target_quant_per_swab ~ svl_mm, data = final_sub_data)

summary(sub_svl_mod)

# Seems longer frogs are less infected


# body_mass_g
sub_bm_mod <- lm(target_quant_per_swab ~ body_mass_g, data = final_sub_data)

summary(sub_bm_mod)

# Seems bigger frogs are less infected...


# svl_mm * body_mass_g
sub_svl.bm_mod <- lm(target_quant_per_swab ~ svl_mm*body_mass_g, data = final_sub_data)

summary(sub_svl.bm_mod)
```


#### Visualize Subadult `lm(target_quant_per_swab ~ svl_mm)`
```{r}

pred_svl_sub <- seq(min(final_sub_data$svl_mm), max(final_sub_data$svl_mm), len=100)

newdata_sub <- data.frame(svl_mm = pred_svl_sub)

mod_pred_adult = predict(sub_svl_mod, newdata = newdata_sub, se.fit = T, type = 'response')
newdata_sub$pred <- mod_pred_adult$fit
newdata_sub$upper_se <- mod_pred_adult$fit + (2 * mod_pred_adult$se.fit)
newdata_sub$lower_se <- mod_pred_adult$fit - (2 * mod_pred_adult$se.fit)

ggplot(newdata_sub) + 
  geom_point(data=final_sub_data, aes(x=svl_mm, y=target_quant_per_swab), size=0.5, alpha = 0.2) +
  geom_line(data=newdata_sub, aes(x=svl_mm, y=pred), linewidth = 1) +
  geom_ribbon(aes(ymin = lower_se, ymax= upper_se, x = svl_mm), alpha = 0.2, fill = "blue") +
  xlab("svl_mm") + ylab("Infection Intensity") + 
  theme_classic() +
  ggtitle(paste("Sub-Adult RAMU, Site 70550, Slope:", 
                round(summary(sub_svl_mod)$coefficients[2,1], 3), 
                ", p-value:", 
                round(summary(sub_svl_mod)$coefficients[2,4], 3), "**"))

```



