---
title: "Size vs. Bd modeling: Panamá preliminary results"
author: Cob Staines
date: 2025-09-29
format:
  html:
    toc: true
df-print: kable
bibliography: references.bib
csl: ecology.csl
---

# setup

```{r}
#| eval: true
#| output: false
#| code-fold: true
#| code-summary: "Show setup code"

# setup
librarian::shelf(tidyverse, dbplyr, here, janitor, RPostgres, DBI, RIBBiTR-BII/ribbitrrr, brms, tidybayes, ggplot2, ggrepel, bayesplot, runner, cmdstanr, bayestestR, emmeans, patchwork, viridis)

```

## Data selection

```{r}
#| eval: false
#| warning: false
#| code-fold: true
#| code-summary: "Show data collection code"

## Connect to DB
dbcon = hopToDB("ribbitr", hopReg = FALSE)

# table pointers
db_bd = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))
db_sample = tbl(dbcon, Id("survey_data", "sample"))
db_capture = tbl(dbcon, Id("survey_data", "capture"))
db_survey = tbl(dbcon, Id("survey_data", "survey"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_region = tbl(dbcon, Id("survey_data", "region"))
db_country = tbl(dbcon, Id("survey_data", "country"))

# preliminary data
bd_sample = db_sample %>%
  right_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(sample_type == "bd",
         taxon_capture %in% c("rana_muscosa",
                              "rana_sierrae")) %>%
  inner_join(db_bd %>%
              filter(!is.na(bd_detected)) %>%
              group_by(sample_id) %>%
              slice_sample(n = 1) %>%
              ungroup() %>%
              select(sample_id,
                     bd_detected,
                     bd_its1_copies_per_swab), by = "sample_id") %>%
  rename(bd_load = bd_its1_copies_per_swab) %>%
  mutate(bd_detected_co = bd_load >= 6,
         bd_load_co = if_else(bd_load < 6,
                                  0,
                                  bd_load),
         bd_load_co_density = bd_load_co / svl_mm)

# load populations
site_year_pop = read.csv(here("data", "sn_resilience_trajectory_classification_pop_lookup_2026-02-28.csv")) %>%
  mutate(site = as.character(site))

# load resilience trajectory classifications
pop_year_class = read.csv(here("data", "sn_resilience_trajectory_classification_2026-02-28.csv"))

# load environmental data
env_agg = read_csv(here("data", "unified_env_agg.csv"))

# define life stage simple
bd_life_stage = bd_sample %>%
  filter(life_stage %in% c("adult",
                           "subadult",
                           NA) |
           tad_stage >= 44) %>%
  mutate(svl_mm = if_else(!is.na(tad_stage) & is.na(svl_mm), 25, svl_mm),
         life_stage_simple = case_when(
    !is.na(tad_stage) | svl_mm < 30 ~ "metamorph",
    is.na(svl_mm) ~ life_stage,
    (svl_mm >= 40) ~ "adult",
    (svl_mm < 40) ~ "subadult",
    .default = NA),
    year = year(date)) %>%
  filter(!is.na(life_stage_simple))

bd_model = bd_life_stage %>%
  filter(site %in% site_year_pop$site) %>%
  select(sample_id,
         bd_detected,
         bd_load,
         bd_detected_co,
         bd_load_co,
         bd_load_co_density,
         sample_name,
         capture_id,
         taxon_capture,
         life_stage,
         tad_stage,
         life_stage_simple,
         svl_mm,
         body_mass_g,
         sex,
         date,
         year,
         site,
         site_id,
         region,
         country) %>%
  collect() %>%
  left_join(site_year_pop, by = c("site", "year")) %>%
  inner_join(pop_year_class %>%
              select(population,
                     year,
                     res_class), by = c("population", "year")) %>%
  left_join(env_agg %>%
              select(site,
                     date,
                     precip_mm_30_day_sum,
                     temp_c_30_day_mean), by = c("site", "date")) %>%
  filter(!is.na(bd_load_co_density)) %>%
  mutate(taxon_life_res = paste(taxon_capture, life_stage_simple, res_class, sep ="_"),
         life_stage_simple = factor(life_stage_simple, levels = c("metamorph", "subadult", "adult")))

write_csv(bd_model, here("data", paste0("sn_res_traj_bd_model_data_", today(), ".csv")))

peace = bd_model %>%
  filter(life_stage_simple == "metamorph")

```

# Load data & descriptive stats
```{r}
#| eval: true
#| warning: false
#| code-fold: true
#| code-summary: "Show descriptive stats code"

bd_model = read.csv(here("data", paste0("sn_res_traj_bd_model_data_2026-03-16.csv")))

bd_model_stats = bd_model %>%
  group_by(taxon_capture,
           res_class,
           life_stage_simple) %>%
  summarize(n = n(),
            .groups= "drop")

```

# Modeling

## Model setup
```{r}
#| code-fold: true
#| code-summary: "Show model setup code"

# unified, scaled model
brms_scales = bd_model %>%
  group_by() %>%
  summarize(precip_mm_30_day_sum_mean = mean(precip_mm_30_day_sum),
            precip_mm_30_day_sum_sd = sd(precip_mm_30_day_sum),
            temp_c_30_day_mean_mean = mean(temp_c_30_day_mean),
            temp_c_30_day_mean_sd = sd(temp_c_30_day_mean),
            precip_mm_30_day_sum2_mean = mean(precip_mm_30_day_sum ^ 2),
            precip_mm_30_day_sum2_sd = sd(precip_mm_30_day_sum ^ 2),
            temp_c_30_day_mean2_mean = mean(temp_c_30_day_mean ^ 2),
            temp_c_30_day_mean2_sd = sd(temp_c_30_day_mean ^ 2))

brms_rescale = function(df, scales) {
  df_out = df %>%
    mutate( precip_mm_30_z = (precip_mm_30_day_sum - scales$precip_mm_30_day_sum_mean)/scales$precip_mm_30_day_sum_sd,
            temp_c_30_z = (temp_c_30_day_mean - scales$temp_c_30_day_mean_mean)/scales$temp_c_30_day_mean_sd,
            precip_mm_30_z2 = (precip_mm_30_day_sum^2 - scales$precip_mm_30_day_sum2_mean)/scales$precip_mm_30_day_sum2_sd,
            temp_c_30_z2 = (temp_c_30_day_mean^2 - scales$temp_c_30_day_mean2_mean)/scales$temp_c_30_day_mean2_sd
    )
}

brms_data = bd_model %>%
  mutate(
    precip_mm_30_z = as.numeric(scale(precip_mm_30_day_sum, center = TRUE, scale = TRUE)),
    temp_c_30_z = as.numeric(scale(temp_c_30_day_mean, center = TRUE, scale = TRUE)),
    precip_mm_30_z2 = as.numeric(scale(precip_mm_30_day_sum ^ 2, center = TRUE, scale = TRUE)),
    temp_c_30_z2 = as.numeric(scale(temp_c_30_day_mean ^ 2, center = TRUE, scale = TRUE))
  )


model_priors <- c(
  # b
  prior(normal(0, 5), class = "Intercept"),
  prior(normal(0, 3),   class = "b"),
  
  # hu
  prior(normal(0, 2), class = "Intercept", dpar = "hu"),
  prior(normal(0, 1), class = "b", dpar = "hu"),
  
  # Sigma
  prior(normal(0, 1), class = "Intercept", dpar = "sigma"),
  prior(normal(0, 0.3), class = "b", dpar = "sigma"),
  
  # Random effects
  prior(exponential(1), class = "sd")
)

set_cmdstan_path(Sys.getenv("cmd_stan_path"))
```

## Model fitting
```{r}
#| eval: false
#| code-fold: true
#| code-summary: "Show model fitting code"

# null model
null_zln <- brm(
  bd_load_co_density ~ 1,
  data = brms_data,
  family = hurdle_lognormal(),
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 124,
  cores = 4,
  backend = "cmdstanr"
)

null_zln = add_criterion(null_zln, "loo")

saveRDS(null_zln, file = here("snrt_models/snrt_model_results_zln_null.rds"))
null_zln = readRDS(file = here("snrt_models/snrt_model_results_zln_null.rds"))


# fixed env
m6_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + life_stage_simple * taxon_capture * res_class + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 | taxon_capture:life_stage_simple) + (1 | population:res_class:life_stage_simple),
    hu ~ 1 + life_stage_simple * taxon_capture * res_class + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 | taxon_capture:life_stage_simple) + (1 | population:res_class:life_stage_simple),
    sigma ~ 1 + life_stage_simple * taxon_capture * res_class + (1 | population:res_class:life_stage_simple)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 124,
  cores = 4,
  backend = "cmdstanr"
)

m6_zln = add_criterion(m6_zln, "loo")

saveRDS(m6_zln, file = "snrt_models/snrt_model_results_zln_life_tax_poptls2envsp2_envsp2.rds")
m6_zln = readRDS(file = "snrt_models/snrt_model_results_zln_life_tax_poptls2envsp2_envsp2.rds")

```


## Model comparison

```{r}
#| eval: false
#| code-fold: true
#| code-summary: "Show model comparison code"
# model comparison and selection

(loo_comp_out = loo_compare(null_zln,
                            m6_zln))
```

## Model report
```{r}
model_select = m6_zln

summary(model_select)
plot((model_select), ask = FALSE)
plot(conditional_effects(model_select), ask = FALSE)

```

## pp_check
```{r}
#| fig-height: 8
#| fig-width: 6
model_select = m6_zln

# all
pp_check(model_select) +
  scale_x_log10()

# break out by taxon_capture, life_stage_simple, res_class

# pp_check(model_select,
#          type = "dens_overlay_grouped",
#          group = "taxon_capture",
#          ndraws = 1000) +
#   scale_x_log10()
# 
# pp_check(model_select,
#          type = "dens_overlay_grouped",
#          group = "life_stage_simple",
#          ndraws = 1000) +
#   scale_x_log10()
# 
# pp_check(model_select,
#          type = "dens_overlay_grouped",
#          group = "res_class",
#          ndraws = 1000) +
#   scale_x_log10()

yrep = posterior_predict(model_select,
                         ndraws = 100)

ind_rm_a_1 = which(brms_data$taxon_capture == "rana_muscosa" &
                     brms_data$life_stage_simple == "adult" &
                     brms_data$res_class == "1-naive")
ind_rm_a_2 = which(brms_data$taxon_capture == "rana_muscosa" &
                     brms_data$life_stage_simple == "adult" &
                     brms_data$res_class == "2-epizootic")
ind_rm_a_3 = which(brms_data$taxon_capture == "rana_muscosa" &
                     brms_data$life_stage_simple == "adult" &
                     brms_data$res_class == "3-post")
ind_rm_s_1 = which(brms_data$taxon_capture == "rana_muscosa" &
                     brms_data$life_stage_simple == "subadult" &
                     brms_data$res_class == "1-naive")
ind_rm_s_2 = which(brms_data$taxon_capture == "rana_muscosa" &
                     brms_data$life_stage_simple == "subadult" &
                     brms_data$res_class == "2-epizootic")
ind_rm_s_3 = which(brms_data$taxon_capture == "rana_muscosa" &
                     brms_data$life_stage_simple == "subadult" &
                     brms_data$res_class == "3-post")
# rana sierrae
ind_rs_a_1 = which(brms_data$taxon_capture == "rana_sierrae" &
                     brms_data$life_stage_simple == "adult" &
                     brms_data$res_class == "1-naive")
ind_rs_a_2 = which(brms_data$taxon_capture == "rana_sierrae" &
                     brms_data$life_stage_simple == "adult" &
                     brms_data$res_class == "2-epizootic")
ind_rs_a_3 = which(brms_data$taxon_capture == "rana_sierrae" &
                     brms_data$life_stage_simple == "adult" &
                     brms_data$res_class == "3-post")
ind_rs_s_1 = which(brms_data$taxon_capture == "rana_sierrae" &
                     brms_data$life_stage_simple == "subadult" &
                     brms_data$res_class == "1-naive")
ind_rs_s_2 = which(brms_data$taxon_capture == "rana_sierrae" &
                     brms_data$life_stage_simple == "subadult" &
                     brms_data$res_class == "2-epizootic")
ind_rs_s_3 = which(brms_data$taxon_capture == "rana_sierrae" &
                     brms_data$life_stage_simple == "subadult" &
                     brms_data$res_class == "3-post")


y_rm_a_1 = brms_data$bd_load_co_density[ind_rm_a_1]
y_rm_a_2 = brms_data$bd_load_co_density[ind_rm_a_2]
y_rm_a_3 = brms_data$bd_load_co_density[ind_rm_a_3]
y_rm_s_1 = brms_data$bd_load_co_density[ind_rm_s_1]
y_rm_s_2 = brms_data$bd_load_co_density[ind_rm_s_2]
y_rm_s_3 = brms_data$bd_load_co_density[ind_rm_s_3]
y_rs_a_1 = brms_data$bd_load_co_density[ind_rs_a_1]
y_rs_a_2 = brms_data$bd_load_co_density[ind_rs_a_2]
y_rs_a_3 = brms_data$bd_load_co_density[ind_rs_a_3]
y_rs_s_1 = brms_data$bd_load_co_density[ind_rs_s_1]
y_rs_s_2 = brms_data$bd_load_co_density[ind_rs_s_2]
y_rs_s_3 = brms_data$bd_load_co_density[ind_rs_s_3]

y_combined = c(y_rm_a_1,
               y_rm_a_2,
               y_rm_a_3,
               y_rm_s_1,
               y_rm_s_2,
               y_rm_s_3,
               y_rs_a_1,
               y_rs_a_2,
               y_rs_a_3,
               y_rs_s_1,
               y_rs_s_2,
               y_rs_s_3)

yrep_combined = cbind(yrep[, ind_rm_a_1],
                      yrep[, ind_rm_a_2],
                      yrep[, ind_rm_a_3],
                      yrep[, ind_rm_s_1],
                      yrep[, ind_rm_s_2],
                      yrep[, ind_rm_s_3],
                      yrep[, ind_rs_a_1],
                      yrep[, ind_rs_a_2],
                      yrep[, ind_rs_a_3],
                      yrep[, ind_rs_s_1],
                      yrep[, ind_rs_s_2],
                      yrep[, ind_rs_s_3])
group_labels = c(rep("rana_muscosa_adult_naive", length(y_rm_a_1)),
                 rep("rana_muscosa_adult_epizootic", length(y_rm_a_2)),
                 rep("rana_muscosa_adult_post", length(y_rm_a_3)),
                 rep("rana_muscosa_subadult_naive", length(y_rm_s_1)),
                 rep("rana_muscosa_subadult_epizootic", length(y_rm_s_2)),
                 rep("rana_muscosa_subadult_post", length(y_rm_s_3)),
                 rep("rana_sierrae_adult_naive", length(y_rs_a_1)),
                 rep("rana_sierrae_adult_epizootic", length(y_rs_a_2)),
                 rep("rana_sierrae_adult_post", length(y_rs_a_3)),
                 rep("rana_sierrae_subadult_naive", length(y_rs_s_1)),
                 rep("rana_sierrae_subadult_epizootic", length(y_rs_s_2)),
                 rep("rana_sierrae_subadult_post", length(y_rs_s_3)))

ppc_dens_overlay_grouped(y_combined,
                         yrep_combined,
                         group = group_labels) +
  scale_x_log10()

```


## Prior checks
```{r}
#| eval: false
#| code-fold: true
#| code-summary: "Show prior checks code"


model_select = m6_zln

get_variables(model_select)


mcmc_plot(model_select, type = "dens", variable = c("prior_Intercept", "prior_b", "b_Intercept", "b_taxon_capturerana_sierrae")) +
  xlim(-10, 10)

mcmc_plot(model_select, type = "dens", variable = c("prior_Intercept_sigma", "prior_b_sigma", "b_sigma_Intercept", "b_sigma_taxon_capturerana_sierrae")) +
  xlim(-2, 2)

mcmc_plot(model_select, type = "dens", variable = c("prior_Intercept_hu", "prior_b_hu", "b_hu_Intercept", "b_hu_taxon_capturerana_sierrae")) +
  xlim(-5, 5)


```

## Define analysis functions
```{r}
#| eval: true
#| warning: false
#| code-fold: true
#| code-summary: "Show processing & visualization functions"

get_species_name = function(taxon, newline = FALSE) {
  species_name = str_to_sentence(gsub("_", " ", taxon))
  if (newline) {
    species_name = gsub(" ", "\n", species_name)
  }
  return(species_name)
}

wilson_ci = function(p_hat, n, conf.level = 0.95) {
  z <- qnorm(1 - (1 - conf.level) / 2)
  
  denominator <- 1 + (z^2 / n)
  centre_adjusted_probability <- p_hat + (z^2 / (2 * n))
  adjusted_standard_deviation <- sqrt((p_hat * (1 - p_hat) / n) + (z^2 / (4 * n^2)))
  
  lower_bound <- (centre_adjusted_probability - z * adjusted_standard_deviation) / denominator
  upper_bound <- (centre_adjusted_probability + z * adjusted_standard_deviation) / denominator
  
  return(c(lower_bound = lower_bound, upper_bound = upper_bound))
}

wilson_ci_lower = function(p_hat, n, conf.level = 0.95) {
  ws = wilson_ci(p_hat, n, conf.level)
  return(ws[1])
}

wilson_ci_upper = function(p_hat, n, conf.level = 0.95) {
  ws = wilson_ci(p_hat, n, conf.level)
  return(ws[2])
}


```

# Results

## Extract and organize draws
```{r}
model_select = m6_zln

# emmeans parameter distributions
## prevalence
hu_specs = emmeans(model_select, 
                   ~ life_stage_simple | taxon_capture * res_class, 
                   dpar = "hu")

contrast(hu_specs, method = "revpairwise") 

hu_contrasts_specs = contrast(hu_specs, method = "revpairwise")

hu_group_draws = hu_specs %>%
  gather_emmeans_draws() %>%
  rename(hu = .value) %>%
  mutate(prevalence = 1 - plogis(hu))

hu_contrast_draws = hu_contrasts_specs %>%
  gather_emmeans_draws() %>%
  rename(hu_subadult = .value)

hu_contrast_agg = hu_contrast_draws %>%
  group_by(taxon_capture,
           res_class,
           contrast,) %>%
  summarize(hdi_50 = hdi(hu_subadult, ci = 0.50),
            hdi_89 = hdi(hu_subadult, ci = 0.89),
            hdi_95 = hdi(hu_subadult, ci = 0.95),
            ratio_positive = sum(hu_subadult > 0) / n(),
            hu_median = median(hu_subadult),
            .groups = "drop") %>%
  mutate(
    hdi_zero_50 = case_when(
      hdi_50$CI_low > 0 | hdi_50$CI_high < 0 ~ TRUE,
      .default = FALSE
    ),
    hdi_zero_89 = case_when(
      hdi_89$CI_low > 0 | hdi_89$CI_high < 0 ~ TRUE,
      .default = FALSE
    ),
    hdi_zero_95 = case_when(
      hdi_95$CI_low > 0 | hdi_95$CI_high < 0 ~ TRUE,
      .default = FALSE
    ))

## b (mu)
b_specs = emmeans(model_select, 
                 ~ life_stage_simple | taxon_capture * res_class, 
                 dpar = "mu")

contrast(b_specs, method = "revpairwise") 

b_contrasts_specs = contrast(b_specs, method = "revpairwise")

b_group_draws = b_specs %>%
  gather_emmeans_draws() %>%
  rename(b = .value)

b_contrast_draws = b_contrasts_specs %>%
  gather_emmeans_draws() %>%
  rename(b_subadult = .value)

b_contrast_agg = b_contrast_draws %>%
  group_by(taxon_capture,
           res_class,
           contrast) %>%
  summarize(hdi_50 = hdi(b_subadult, ci = 0.50),
            hdi_89 = hdi(b_subadult, ci = 0.89),
            hdi_95 = hdi(b_subadult, ci = 0.95),
            ratio_positive = sum(b_subadult > 0) / n(),
            b_median = median(b_subadult),
            .groups = "drop") %>%
  mutate(
    hdi_zero_50 = case_when(
      hdi_50$CI_low > 0 | hdi_50$CI_high < 0 ~ TRUE,
      .default = FALSE
    ),
    hdi_zero_89 = case_when(
      hdi_89$CI_low > 0 | hdi_89$CI_high < 0 ~ TRUE,
      .default = FALSE
    ),
    hdi_zero_95 = case_when(
      hdi_95$CI_low > 0 | hdi_95$CI_high < 0 ~ TRUE,
      .default = FALSE
    ))

## sigma
sigma_specs = emmeans(model_select, 
                 ~ life_stage_simple | taxon_capture * res_class, 
                 dpar = "sigma")

contrast(sigma_specs, method = "revpairwise") 

sigma_contrasts_specs = contrast(sigma_specs, method = "revpairwise")

sigma_group_draws = sigma_specs %>%
  gather_emmeans_draws() %>%
  rename(sigma = .value)

sigma_contrast_draws = sigma_contrasts_specs %>%
  gather_emmeans_draws() %>%
  rename(sigma_subadult = .value)

sigma_contrast_agg = sigma_contrast_draws %>%
  group_by(taxon_capture,
           res_class,
           contrast) %>%
  summarize(hdi_50 = hdi(sigma_subadult, ci = 0.50),
            hdi_89 = hdi(sigma_subadult, ci = 0.89),
            hdi_95 = hdi(sigma_subadult, ci = 0.95),
            ratio_positive = sum(sigma_subadult > 0) / n(),
            sigma_median = median(sigma_subadult),
            .groups = "drop") %>%
  mutate(
    hdi_zero_50 = case_when(
      hdi_50$CI_low > 0 | hdi_50$CI_high < 0 ~ TRUE,
      .default = FALSE
    ),
    hdi_zero_89 = case_when(
      hdi_89$CI_low > 0 | hdi_89$CI_high < 0 ~ TRUE,
      .default = FALSE
    ),
    hdi_zero_95 = case_when(
      hdi_95$CI_low > 0 | hdi_95$CI_high < 0 ~ TRUE,
      .default = FALSE
    ))

# combine
contrast_agg = hu_contrast_agg %>%
  left_join(b_contrast_agg, by = c("taxon_capture", "res_class", "contrast"), suffix = c("_hu", "_b")) %>%
  left_join(sigma_contrast_agg, by = c("taxon_capture", "res_class", "contrast")) %>%
  mutate(net_effect_hu = ratio_positive_hu * 2 - 1,
         net_effect_b = ratio_positive_b * 2 - 1,
         net_effect_sigma = ratio_positive * 2 - 1)

group_draws = b_group_draws %>%
  left_join(hu_group_draws, by = c(".chain", ".iteration", ".draw", 
                                   "life_stage_simple", "taxon_capture", "res_class")) %>%
  left_join(sigma_group_draws, by = c(".chain", ".iteration", ".draw", 
                                      "life_stage_simple", "taxon_capture", "res_class")) %>%
  mutate(life_stage_simple = factor(life_stage_simple, levels = c("metamorph", "subadult", "adult")))

group_draws_agg = group_draws %>%
  group_by(taxon_capture,
           life_stage_simple,
           res_class) %>%
  summarize(hu_median = median(hu),
            prevalence_median = median(prevalence),
            b_median = median(b),
            sigma_median = median(hu),
            .groups = "drop")

# epred draws
newdata_basic = expand_grid(taxon_capture = c("rana_muscosa",
                                              "rana_sierrae"),
                            life_stage_simple = c("metamorph",
                                                  "subadult",
                                                  "adult"),
                            res_class = c("1-naive",
                                          "2-epizootic",
                                          "3-post")) %>%
  mutate(precip_mm_30_z = 0,
         precip_mm_30_z2 = 0,
         temp_c_30_z = 0,
         temp_c_30_z2 = 0)

# way too big!
epred_original = epred_draws(model_select,
                             newdata = brms_data,
                             re_formula = NA,
                             ndraws = 50) %>%
  rename(bd_load_density_epred = .epred) %>%
  mutate(life_stage_simple = factor(life_stage_simple, levels = c("metamorph", "subadult", "adult")))

epred_fixed = epred_draws(model_select,
                          newdata = newdata_basic,
                          re_formula = NA) %>%
  rename(bd_load_density_epred = .epred) %>%
  mutate(life_stage_simple = factor(life_stage_simple, levels = c("metamorph", "subadult", "adult")))

# observation data
obs_data = brms_data %>%
  group_by(taxon_capture,
           life_stage_simple,
           res_class) %>%
   summarise(n = n(),
             n_pos = sum(bd_detected_co),
             bd_prevalence = sum(bd_detected_co) / n(),
             bd_prevalence_ci_lower = wilson_ci_lower(bd_prevalence, n(), 0.95),
             bd_prevalence_ci_upper = wilson_ci_upper(bd_prevalence, n(), 0.95),
             min_load_inf = min(bd_load_co_density[bd_detected_co > 0]),
             q_25_load_inf = quantile(bd_load_co_density[bd_detected_co > 0], probs = 0.25),
             q_50_load_inf = quantile(bd_load_co_density[bd_detected_co > 0], probs = 0.50),
             q_75_load_inf = quantile(bd_load_co_density[bd_detected_co > 0], probs = 0.75),
             max_load_inf = max(bd_load_co_density[bd_detected_co > 0]),
             se = sqrt(bd_prevalence*(1-bd_prevalence)/n),
             .groups = "drop") %>%
  mutate(label_offset = recode_values(life_stage_simple,
                                      "adult" ~ 0,
                                      "subadult" ~ 0.5,
                                      "metamorph" ~ 1),
         life_stage_simple = factor(life_stage_simple, levels = c("metamorph", "subadult", "adult")))


```

## Visualize outputs

### Prevalence
```{r}
# observed
ggplot(obs_data, aes(y = bd_prevalence, x = res_class, color = life_stage_simple)) +
  geom_point(position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = bd_prevalence_ci_lower, ymax = bd_prevalence_ci_upper),
                width = 0.2,
                position = position_dodge(width = 0.5)) +
  geom_text(aes(label = paste0("n=", n), y = 1.1 - (1 - label_offset) * 0.075),
          position = position_dodge(width = 0.5),
          size = 4) +
  ylim(0, 1.1) +
  theme_minimal() +
  facet_wrap("taxon_capture") +
  scale_color_brewer(palette = "Set2")

# modeled
ggplot(group_draws, aes(y = prevalence, x = res_class, fill = life_stage_simple)) +
  geom_violin(quantiles = c(0.5),
              quantile.linetype = 1) +
  theme_minimal() +
  facet_wrap("taxon_capture") +
  scale_fill_brewer(palette = "Set2")


```

### Load
```{r}
# observed
ggplot(brms_data %>%
         filter(bd_detected_co > 0), aes(y = bd_load_co_density, x = res_class, fill = life_stage_simple)) +
  geom_violin(quantiles = c(0.5),
              quantile.linetype = 1) +
  geom_text(data = obs_data, aes(label = paste0("n=", n_pos), y = 10e8 - (1 - label_offset) * 7 * 10e7),
            position = position_dodge(width = 0.5),
            size = 4) +
  scale_y_log10(limits = c(1, 1e10)) +
  theme_minimal() +
  facet_wrap("taxon_capture") +
  scale_fill_brewer(palette = "Set2")

# ggplot(epred_original, aes(y = bd_load_density_epred, x = res_class, fill = life_stage_simple)) +
#   geom_violin() +
#   # geom_boxplot() +
#   scale_y_log10(limits = c(1, 1e10)) +
#   theme_minimal() +
#   facet_wrap("taxon_capture") +
#   scale_fill_brewer(palette = "Set2")

ggplot(epred_fixed, aes(y = bd_load_density_epred, x = res_class, fill = life_stage_simple)) +
  geom_violin(quantiles = c(0.5),
              quantile.linetype = 1) +
  # geom_boxplot() +
  scale_y_log10(limits = c(1, 1e10)) +
  theme_minimal() +
  facet_wrap("taxon_capture") +
  scale_fill_brewer(palette = "Set2")



```

### Hypothesis testing
```{r}
#| eval: true
#| echo: false
#| warning: false


# visualize draws
ggplot(group_draws_agg, aes(x = prevalence_median, y = b_median, color = life_stage_simple)) +
  geom_point() +
  geom_path() +
  theme_minimal() +
  geom_text_repel(aes(label = res_class), seed = 123) +
  facet_wrap("taxon_capture") +
  scale_color_brewer(palette = "Set2")

ggplot(group_draws, aes(x = prevalence, y = b, color = life_stage_simple)) +
  geom_point(alpha = 0.1) +
  theme_minimal() +
  facet_grid(res_class ~ taxon_capture) +
  scale_color_brewer(palette = "Set2")

# single parameter distributions

ggplot(group_draws, aes(y = prevalence, x = res_class, color = life_stage_simple)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  theme_minimal() +
  facet_wrap("taxon_capture") +
  scale_color_brewer(palette = "Set2")

ggplot(group_draws, aes(y = b, x = res_class, color = life_stage_simple)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  theme_minimal() +
  facet_wrap("taxon_capture") +
  scale_color_brewer(palette = "Set2")

ggplot(group_draws, aes(y = sigma, x = res_class, color = life_stage_simple)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  theme_minimal() +
  facet_wrap("taxon_capture") +
  scale_color_brewer(palette = "Set2")

# visualize contrasts
ggplot(hu_contrast_draws %>%
         filter(contrast != "subadult - metamorph"), aes(x = hu_subadult, fill = contrast)) +
  stat_halfeye(alpha = 0.75,
               .width = c(0.5, 0.89),
               point_interval = mode_hdi) +
  facet_grid(res_class ~ taxon_capture) +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
       # title = "Subadult Effect on Bd Prevalence",
       x = "Bd Prevalence Effect Size Contrast (logit scale) [-]\nwith 50% & 89% High Density Interval",
       y = "Posterior Density [-]") +
  theme(text=element_text(size=14)) +
  scale_fill_brewer(palette = "Set2")

ggplot(b_contrast_draws %>%
         filter(contrast != "subadult - metamorph"), aes(x = b_subadult, fill = contrast)) +
    stat_halfeye(alpha = 0.75,
               .width = c(0.5, 0.89),
               point_interval = mode_hdi) +
  facet_grid(res_class ~ taxon_capture) +
  geom_vline(xintercept = 0, alpha = 0.5) +
  theme_minimal() +
  labs(
       # title = "Subadult Effect on Bd Prevalence",
       x = "Bd Load Density Effect Size Contrast (logit scale) [-]\nwith 50% & 89% High Density Interval",
       y = "Posterior Density [-]") +
  theme(text=element_text(size=14)) +
  scale_fill_brewer(palette = "Set2")

ggplot(sigma_contrast_draws %>%
         filter(contrast != "subadult - metamorph"), aes(x = sigma_subadult, fill = contrast)) +
  stat_halfeye(alpha = 0.75,
               .width = c(0.5, 0.89),
               point_interval = mode_hdi) +
  facet_grid(res_class ~ taxon_capture) +
  geom_vline(xintercept = 0, alpha = 1) +
  theme_minimal() +
  labs(
    # title = "Subadult Effect on Bd Prevalence",
    x = "Bd Load Sigma Effect Size Contrast (logit scale) [-]\nwith 50% & 89% High Density Interval",
    y = "Posterior Density [-]") +
  theme(text=element_text(size=14)) +
  scale_fill_brewer(palette = "Set2")

# probability of positive effect
ggplot(contrast_agg %>%
         filter(contrast != "subadult - metamorph"), aes(x = net_effect_hu, y = net_effect_b, color = contrast)) +
  geom_vline(xintercept = 0, color = "#aaa") +
  geom_hline(yintercept = 0, color = "#aaa") + 
  geom_point() +
  geom_path() +
  geom_text_repel(aes(label = res_class), seed = 123) +
  xlim(-1, 1) +
  ylim(-1, 1) +
  theme_minimal() +
  labs(
       # title = "Subadult Effect: Fraction Above Zero (FAZ)",
       x = "Bd Prevalence\nNet effect relative to adult [-]",
       y = "Bd Load Density\nNet effect relative to adult[-]") +
  scale_color_brewer(palette = "Set2") +
  facet_wrap("taxon_capture")

ggplot(contrast_agg %>%
         filter(contrast != "subadult - metamorph"), aes(x = hu_median, y = b_median, color = contrast)) +
  geom_vline(xintercept = 0, color = "#aaa") +
  geom_hline(yintercept = 0, color = "#aaa") + 
  geom_point() +
  geom_path() +
  geom_text_repel(aes(label = res_class), seed = 123) +
  theme_minimal() +
  labs(
       # title = "Subadult Effect: Fraction Above Zero (FAZ)",
       x = "Bd Prevalence\nMedian effect relative to adult [-]",
       y = "Bd Load Density\nMedian effect relative to adult [-]") +
  scale_color_brewer(palette = "Set2") +
  facet_wrap("taxon_capture")

ggplot(contrast_agg %>%
         filter(contrast != "subadult - metamorph"), aes(x = hu_median, y = sigma_median, color = contrast)) +
  geom_vline(xintercept = 0, color = "#aaa") +
  geom_hline(yintercept = 0, color = "#aaa") + 
  geom_point() +
  geom_path() +
  geom_text_repel(aes(label = res_class), seed = 123) +
  theme_minimal() +
  labs(
       # title = "Subadult Effect: Fraction Above Zero (FAZ)",
       x = "Bd Hu\nMedian effect relative to adult [-]",
       y = "Bd Load Density Dispersion\nMedian effect relative to adult [-]") +
  scale_color_brewer(palette = "Set2") +
  facet_wrap("taxon_capture")


```
