---
title: "01_GAM_survey_data"
output: html_document
---

# Setup

```{r}
#| eval: true
#| output: false
#| code-fold: true
#| code-summary: "Show setup code"

# setup
librarian::shelf(tidyverse,  RPostgres, DBI, RIBBiTR-BII/ribbitrrr, dbplyr, janitor, here, brms, cmdstanr, tidybayes, patchwork, terra)

```

# Data selection

## environmental
```{r}
env_agg = read_csv(here("data", "unified_env_agg.csv"))

# env standardization from the unified model data (m11d_co100 was fit to this file)
load(here("size_bd_unified", "intermediates", "bd_model_env_unified_2026-09-23.RData"))

unified_env_scale = list(
  precip_mean = mean(brms_data$precip_mm_10_day_sum),
  precip_sd = sd(brms_data$precip_mm_10_day_sum),
  temp_mean = mean(brms_data$temp_c_30_day_mean),
  temp_sd = sd(brms_data$temp_c_30_day_mean))

rm(brms_data)

# to_life_stage_simple = function(df, taxa, group_name, svl_min, svl_max) {
#   df_out = df
# }

```

# RACA
```{r}
raca_raw = read.csv(here("data", "JPSL_RACA_Swabbed_Individuals_2026-03-03.csv")) %>%
  clean_names()

met_med = raca_raw %>%
  filter(life_stage == "M",
         !is.na(svl_mm)) %>%
  summarize(mm = median(svl_mm))

raca_clean = raca_raw %>%
  filter(life_stage %in% c("A", "S", "Y", "M")) %>%
  dplyr::rename(site = site_name,
         body_mass_g = weight_g,
         site_utme = utme_site,
         site_utmn = utmn_site,
         bd_its1_copies_per_swab = bd_swab_results_its) %>%
  mutate(date = as.Date(date),
         life_stage_simple = case_when(
           life_stage == "M" ~ "metamorph",
           svl_mm >= 50 ~ "adult",
           svl_mm < 50 ~ "subadult"),
         svl_mm = if_else(life_stage_simple == "metamorph" & is.na(svl_mm), 25, svl_mm),
         site = tolower(gsub(" ", "_", site)),
         site_utm_zone = 11,  # verify
         population = site,
         region = "W",
         country = "usa",
         project = "RACA",
         taxon_capture = "rana_cascadae") %>%
  filter(!is.na(bd_its1_copies_per_swab)) %>%
  mutate(year = year(date))

raca_valid = raca_clean %>%
  select(taxon_capture,
         date,
         year,
         site,
         population,
         bd_its1_copies_per_swab,
         life_stage_simple,
         life_stage,
         sex,
         svl_mm,
         body_mass_g,
         region,
         country,
         project)
```

# USGS
```{r}

## laod USGS data
usgs_raw = read.csv(here("data", "USGSBsalBdDataFull.csv"))

usgs_clean = usgs_raw %>%
  clean_names() %>%
  dplyr::rename(site_latitude = latitude,
         site_longitude = longitude,
         svl_mm = body_length,
         life_stage = age,
         region = reg,
         bd_its1_copies_per_swab = copy_num) %>%
  mutate(taxon_capture = tolower(gsub(" ", "_", scientific_name)),
         life_stage_simple = tolower(life_stage),
         life_stage_simple = recode_values(life_stage_simple,
                                        "juvenile" ~ "subadult",
                                        default = life_stage_simple),
         date = mdy(collection_date),
         site = paste0("usgs_", site_id),
         population = site,
         year = year(date),
         project = "usgs",
         country = "usa") %>%
  filter(taxon_capture == "notophthalmus_viridescens",
         !is.na(taxon_capture),
         !is.na(bd_its1_copies_per_swab),
         !is.na(svl_mm),
         life_stage_simple %in% c("subadult", "adult"),
         svl_mm <= 200)

usgs_taxon_valid = usgs_clean %>%
  group_by(taxon_capture) %>%
  summarize(n_adult = sum(life_stage_simple == "adult"),
            n_subadult = sum(life_stage_simple == "subadult"),
            .groups = "drop") %>%
  filter(n_adult >= 14,
         n_subadult >= 14,
         taxon_capture != "lithobates_chiricahuensis")

usgs_valid = usgs_clean %>%
  filter(taxon_capture %in% usgs_taxon_valid$taxon_capture) %>%
  select(taxon_capture,
         svl_mm,
         sex,
         life_stage_simple,
         life_stage,
         date,
         year,
         bd_its1_copies_per_swab,
         site,
         site_latitude,
         site_longitude,
         population,
         region,
         country,
         project)

usgs_spp = usgs_valid %>%
  group_by(taxon_capture,
           life_stage_simple) %>%
  count()
```


# RIBBiTR
```{r}
## Connect to DB
dbcon = hopToDB("railway", hopReg = FALSE)

# table pointers
db_bd = tbl(dbcon, Id("survey_data", "bd_qpcr_results"))
db_sample = tbl(dbcon, Id("survey_data", "sample"))
db_capture = tbl(dbcon, Id("survey_data", "capture"))
db_survey = tbl(dbcon, Id("survey_data", "survey"))
db_visit = tbl(dbcon, Id("survey_data", "visit"))
db_site = tbl(dbcon, Id("survey_data", "site"))
db_region = tbl(dbcon, Id("survey_data", "region"))
db_country = tbl(dbcon, Id("survey_data", "country"))

# preliminary data
bd_sample = db_sample %>%
  right_join(db_capture, by = "capture_id") %>%
  left_join(db_survey, by = "survey_id") %>%
  left_join(db_visit, by = "visit_id") %>%
  left_join(db_site, by = "site_id") %>%
  left_join(db_region, by = "region_id") %>%
  left_join(db_country, by = "country_id") %>%
  filter(sample_type == "bd") %>%
  inner_join(db_bd %>%
              filter(!is.na(bd_detected)) %>%
              group_by(sample_id) %>%
              slice_sample(n = 1) %>%
              ungroup() %>%
              select(sample_id,
                     bd_its1_copies_per_swab), by = "sample_id")

# load populations
# site_year_pop = read.csv(here("data", "sn_resilience_trajectory_classification_pop_lookup_2026-02-28.csv")) %>%
#   mutate(site = as.character(site))

pops_in = read.csv(here("data", "size_load_pop_1_2026-09-11.csv"))

all_populations = pops_in %>%
  select(site, pop_id) %>%
  dplyr::rename(population = pop_id) %>%
  mutate(population = if_else(!is.na(population), paste0(as.character(population), "_pop"), site),
         site = as.character(site)) %>%
  select(site,
         population)

# define life stage simple
bd_life_stage_ranarasi = bd_sample %>%
  filter(taxon_capture %in% c("rana_muscosa",
                              "rana_sierrae"),
         life_stage %in% c("adult",
                           "subadult",
                           NA) |
           tad_stage >= 44) %>%
  mutate(svl_mm = if_else(!is.na(tad_stage) & is.na(svl_mm), 25, svl_mm),
         life_stage_simple = case_when(
           !is.na(tad_stage) | ((svl_mm >= 20) & svl_mm < 30) ~ "metamorph",
           (svl_mm >= 40) ~ "adult",
           (svl_mm >= 20) & (svl_mm < 40) ~ "subadult",
           .default = NA),
         svl_mm = if_else(life_stage_simple == "metamorph" & is.na(svl_mm), 25, svl_mm)) %>%
  filter(!is.na(life_stage_simple)) %>%
  mutate(year = year(date))

bd_life_stage_panama = bd_sample %>%
  filter(taxon_capture %in% c("colostethus_panamansis",
                              "lithobates_warszewitschii",
                              "silverstoneia_flotator"),
         life_stage != "larva") %>%
  mutate(life_stage_simple = case_when(
    life_stage == "metamorphosed" ~ "metamorph",
    ((taxon_capture == "colostethus_panamansis") & (svl_mm >= 18.8) & (svl_mm < 50)) ~ "adult",
    ((taxon_capture == "colostethus_panamansis") & (svl_mm >= 10) & (svl_mm < 18.8)) ~ "subadult",
    ((taxon_capture == "lithobates_warszewitschii") & (svl_mm >= 35) & (svl_mm < 100)) ~ "adult",
    ((taxon_capture == "lithobates_warszewitschii") & (svl_mm >= 10) & (svl_mm < 35)) ~ "subadult",
    ((taxon_capture == "silverstoneia_flotator") & (svl_mm >= 15.1) & (svl_mm < 25)) ~ "adult",
    ((taxon_capture == "silverstoneia_flotator") & (svl_mm >= 8) & (svl_mm < 15.1)) ~ "subadult",
    .default = NA),
    svl_mm = case_when(
      taxon_capture == "colostethus_panamansis" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 12,
      taxon_capture == "lithobates_warszewitschii" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 20,
      taxon_capture == "silverstoneia_flotator" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 10,
      .default = svl_mm),
    population = region) %>%
  filter(!is.na(svl_mm),
         !is.na(life_stage_simple)) %>%
  mutate(year = year(date))

bd_life_stage_nae = bd_sample %>%
  filter(taxon_capture %in% c("rana_catesbeiana",
                              "rana_pipiens",
                              "rana_clamitans",
                              "pseudacris_crucifer",
                              "lithobates_chiricahuensis",
                              "lithobates_sphenocephalus"),
         !(life_stage %in% c("larva"))) %>%
  mutate(life_stage_simple = case_when(
    life_stage == "metamorph" ~ "metamorph",
    ((taxon_capture == "pseudacris_crucifer") & (svl_mm >= 20) & (svl_mm < 40)) ~ "adult",
    ((taxon_capture == "pseudacris_crucifer") & (svl_mm >= 5) & (svl_mm < 20)) ~ "subadult",
    ((taxon_capture == "rana_catesbeiana") & (svl_mm >= 95) & (svl_mm < 200)) ~ "adult",
    ((taxon_capture == "rana_catesbeiana") & (svl_mm >= 10) & (svl_mm < 95)) ~ "subadult",
    ((taxon_capture == "rana_clamitans") & (svl_mm >= 60) & (svl_mm < 110)) ~ "adult",
    ((taxon_capture == "rana_clamitans") & (svl_mm >= 10) & (svl_mm < 60)) ~ "subadult",
    ((taxon_capture == "rana_pipiens") & (svl_mm >= 51) & (svl_mm < 100)) ~ "adult",
    ((taxon_capture == "rana_pipiens") & (svl_mm >= 10) & (svl_mm < 51)) ~ "subadult",
    ((taxon_capture == "lithobates_chiricahuensis") & (svl_mm >= 57) & (svl_mm < 100)) ~ "adult",
    ((taxon_capture == "lithobates_chiricahuensis") & (svl_mm >= 10) & (svl_mm < 57)) ~ "subadult",
    ((taxon_capture == "lithobates_sphenocephalus") & (svl_mm >= 51) & (svl_mm < 100)) ~ "adult",
    ((taxon_capture == "lithobates_sphenocephalus") & (svl_mm >= 10) & (svl_mm < 51)) ~ "subadult",
    .default = NA),
    svl_mm = case_when(
      taxon_capture == "pseudacris_crucifer" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 13,
      taxon_capture == "rana_catesbeiana" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 30,
      taxon_capture == "rana_clamitans" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 28,
      taxon_capture == "rana_pipiens" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 25,
      taxon_capture == "lithobates_chiricahuensis" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 40,
      taxon_capture == "lithobates_sphenocephalus" & life_stage_simple == "metamorph" & is.na(svl_mm) ~ 29,
      .default = svl_mm),
    population = site) %>%
  filter(!is.na(svl_mm),
         !is.na(life_stage_simple)) %>%
  mutate(year = year(date))


ranarasi_valid = bd_life_stage_ranarasi %>%
  filter(site %in% all_populations$site) %>%
  select(sample_id,
         bd_its1_copies_per_swab,
         sample_name,
         capture_id,
         taxon_capture,
         life_stage,
         tad_stage,
         life_stage_simple,
         svl_mm,
         body_mass_g,
         sex,
         date,
         year,
         site,
         site_id,
         site_latitude,
         site_longitude,
         region,
         country) %>%
  collect() %>%
  left_join(all_populations, by = "site") %>%
  filter(!is.na(bd_its1_copies_per_swab)) %>%
  mutate(year = year(date))

panama_valid = bd_life_stage_panama %>%
  select(sample_id,
         bd_its1_copies_per_swab,
         sample_name,
         capture_id,
         taxon_capture,
         life_stage,
         tad_stage,
         life_stage_simple,
         svl_mm,
         body_mass_g,
         sex,
         date,
         year,
         site,
         site_id,
         site_latitude,
         site_longitude,
         population,
         region,
         country) %>%
  collect() %>%
  filter(!is.na(bd_its1_copies_per_swab))

nae_valid = bd_life_stage_nae %>%
  select(sample_id,
         bd_its1_copies_per_swab,
         sample_name,
         capture_id,
         taxon_capture,
         life_stage,
         tad_stage,
         life_stage_simple,
         svl_mm,
         body_mass_g,
         sex,
         date,
         year,
         site,
         site_id,
         site_latitude,
         site_longitude,
         population,
         region,
         country) %>%
  collect() %>%
  filter(!is.na(bd_its1_copies_per_swab))

```


# Combine data
```{r}
col_compare = compare_df_cols(ranarasi_valid,
                              raca_valid,
                              panama_valid,
                              nae_valid,
                              usgs_valid)

brms_data = bind_rows(ranarasi_valid,
                      raca_valid,
                      panama_valid,
                      nae_valid,
                              usgs_valid) %>%
  left_join(env_agg %>%
              select(date,
                     site,
                     precip_mm_10_day_sum,
                     temp_c_30_day_mean), by = c("site", "date")) %>%
  mutate(life_stage_simple = factor(life_stage_simple, levels = c("metamorph", "subadult", "adult")),
         is_metamorph = as.numeric(life_stage_simple == "metamorph"),
         is_not_metamorph = as.numeric(life_stage_simple != "metamorph"),
         bd_load_co100 = if_else(bd_its1_copies_per_swab < 100,
                                 0,
                                 bd_its1_copies_per_swab),
         bd_detected_co100 = bd_load_co100 > 0,
         bd_load_co100_density = bd_load_co100 / svl_mm) %>%
  # standardize with the unified data's mean/sd so env slopes (and priors from the
  # unified model) are on the same scale
  mutate(
    precip_mm_10_z = (precip_mm_10_day_sum - unified_env_scale$precip_mean) / unified_env_scale$precip_sd,
    temp_c_30_z = (temp_c_30_day_mean - unified_env_scale$temp_mean) / unified_env_scale$temp_sd)

# check for good alignment with environmental data
env_alignment_check = any(is.na(brms_data$precip_mm_10_day_sum)) | any(is.na(brms_data$temp_c_30_day_mean))

```

# KG zones
```{r}
# use the unified pipeline's site-level KG assignments (size_bd_unified/01_survey_data.Rmd)
unified_sites_kg = read_csv(here("size_bd_unified", "intermediates", "size_bd_modeling_sites.csv")) %>%
  mutate(site = as.character(site)) %>%
  select(site,
         kg_id,
         kg_code_1,
         kg_code_2,
         kg_code_3)

# fallback: extract KG for any GAM sites not in the unified site table, as in the unified pipeline
kg_key = read_csv(here("data", "koppen_geiger_tif", "legend.csv")) %>%
  select(-rgb) %>%
  rename_with(function(x) { paste0("kg_", x) })

missing_sites = brms_data %>%
  filter(!(site %in% unified_sites_kg$site)) %>%
  group_by(site) %>%
  summarise(site_latitude = mean(site_latitude, na.rm = TRUE),
            site_longitude = mean(site_longitude, na.rm = TRUE),
            .groups = "drop")

if (nrow(missing_sites) > 0) {
  kg_rast = rast(here("data", "koppen_geiger_tif", "1991_2020", "koppen_geiger_0p00833333.tif"))

  missing_sites_kg = missing_sites %>%
    bind_cols(extract(kg_rast, cbind(lon = missing_sites$site_longitude,
                                     lat = missing_sites$site_latitude))) %>%
    dplyr::rename(kg_id = koppen_geiger_0p00833333) %>%
    mutate(kg_id = if_else(kg_id == 29, 19, kg_id)) %>%
    left_join(kg_key, by = "kg_id") %>%
    select(site,
           kg_id,
           kg_code_1,
           kg_code_2,
           kg_code_3)

  unified_sites_kg = bind_rows(unified_sites_kg, missing_sites_kg)
}

missing_sites

brms_data = brms_data %>%
  left_join(unified_sites_kg, by = "site")

# checks
check_na_cols = c("bd_load_co100_density",
                  "life_stage_simple",
                  "taxon_capture",
                  "precip_mm_10_z",
                  "temp_c_30_z",
                  "kg_code_3",
                  "population",
                  "date",
                  "year")

(na_col_check = brms_data %>%
  summarise(across(all_of(check_na_cols), ~ sum(is.na(.)))) %>%
  pivot_longer(everything(), names_to = "column", values_to = "n_na"))

if (sum(na_col_check$n_na) > 0) {
  warning("NAs found in model variable columns. Please review.")
}

save(brms_data, file = here("size_bd_gam", "intermediates", paste0("brms_data_gam_", today(), ".RData")))
load(here("size_bd_gam", "intermediates", "brms_data_gam_2026-10-02.RData"))

```

# visualize size distributions
```{r}

peace = brms_data %>%
  group_by(taxon_capture, life_stage_simple) %>%
  count()

peace = brms_data %>%
  filter(taxon_capture %in% c("notophthalmus_viridescens"))

ggplot(brms_data, aes(x = svl_mm, color = life_stage_simple)) +
  geom_histogram() +
  facet_wrap("taxon_capture",
             scale = "free")
```