---
title: "03_size_bd_GAM_analysis"
output: html_document
---

```{r}
#| eval: true
#| output: false
#| code-fold: true
#| code-summary: "Show setup code"

# setup
librarian::shelf(tidyverse, janitor, here, tidybayes, patchwork, arrow)

```

# load models
```{r}

# taxon names
taxon_list = list("colostethus_panamansis",
                  "lithobates_warszewitschii",
                  "pseudacris_crucifer",
                  "rana_cascadae",
                  "rana_catesbeiana",
                  "rana_clamitans",
                  "rana_muscosa",
                  "rana_pipiens",
                  "rana_sierrae",
                  "silverstoneia_flotator")

# list of all models
model_list = map(taxon_list, ~readRDS(file = here(paste0("size_bd_gam/models/size_bd_gam_model_zln_m3_", .x, ".rds"))))

# subadult cutoffs
co_list = c(18.8,
            35,
            20,
            50,
            95,
            60,
            40,
            51,
            40,
            15.1)

```

# visualize results

## epred draws with svl
```{r}
metamorph_svl_prev_epred = function(species_fit, cutoff_mm, taxon_capture) {
  species_data = species_fit$data
  
  # model for median subadult weather
  precip_10_z_subadult_med = species_data %>%
    filter(life_stage_simple == "subadult") %>%
    summarize(precip_10_med = median(precip_mm_10_z)) %>%
    pull(precip_10_med)
  
  temp_30_z_subadult_med = species_data %>%
    filter(life_stage_simple == "subadult") %>%
    summarize(temp_30_med = median(temp_c_30_z)) %>%
    pull(temp_30_med)
  
  # check if at least one metamorph in sample data
  life_stage_counts = species_data %>%
    group_by(life_stage_simple) %>%
    count()
  
  # draws for metamorph
  if ("metamorph" %in% life_stage_counts$life_stage_simple) {
    # metamorph: svl_mm is irrelevant (smooth is off), use a dummy value
    nd_met <- tibble(
      svl_mm           = mean(species_data$svl_mm, na.rm = TRUE),  # doesn't matter
      is_metamorph     = 1,
      is_not_metamorph = 0,
      precip_mm_10_z  = precip_10_z_subadult_med,
      precip_mm_10_z2 = precip_10_z_subadult_med ^ 2,
      temp_c_30_z     = temp_30_z_subadult_med,
      temp_c_30_z2    = temp_30_z_subadult_med ^ 2
    )
    
    # metamorph — keep all draws for boxplot distribution
    hu_met      <- nd_met    |> add_epred_draws(species_fit, dpar = "hu",  re_formula = NA)
    
    # aggregate metamorph stats
    prev_met_agg = hu_met |>
      mutate(prevalence = 1 - plogis(hu)) |>
      median_qi(prevalence, .width = c(0.5, 0.95)) |>
      pivot_wider(id_cols = c(svl_mm, prevalence, is_metamorph),
                  names_from = .width,
                  values_from = c(.lower, .upper))
  } else {
    prev_met_agg = tibble(is_metamorph = 1)
  }
  
  
  # draws for post-metamorphs
  nd_notmet <- tibble(
    svl_mm          = seq(min(species_data$svl_mm, na.rm = TRUE),
                          max(species_data$svl_mm, na.rm = TRUE),
                          length.out = 200),
    is_metamorph    = 0,
    is_not_metamorph = 1,
    precip_mm_10_z  = precip_10_z_subadult_med,
    precip_mm_10_z2 = precip_10_z_subadult_med ^ 2,
    temp_c_30_z     = temp_30_z_subadult_med,
    temp_c_30_z2    = temp_30_z_subadult_med ^ 2
  )
  
  hu_notmet   <- nd_notmet |> add_epred_draws(species_fit, dpar = "hu",  re_formula = NA)
  
  # post-metamorph: median + interval over svl sequence
  prev_notmet_agg <- hu_notmet |>
    mutate(prevalence = 1 - plogis(hu)) |>    # adjust if hu is already on prob scale
    group_by(svl_mm) |>
    median_qi(prevalence, .width = c(0.5, 0.95)) |>
    pivot_wider(id_cols = c(svl_mm, prevalence),
                names_from = .width,
                values_from = c(.lower, .upper)) %>%
    mutate(is_metamorph = 0)
  
  # aggregate post-metamorph stats
  prev_agg = bind_rows(prev_met_agg,
                       prev_notmet_agg) %>%
    mutate(taxon_capture = taxon_capture,
           svl_mm_cutoff = cutoff_mm)
  
  return(prev_agg)
}

metamorph_svl_load_epred = function(species_fit, cutoff_mm, taxon_capture) {
  species_data = species_fit$data
  
  # model for median subadult weather
  precip_10_z_subadult_med = species_data %>%
    filter(life_stage_simple == "subadult") %>%
    summarize(precip_10_med = median(precip_mm_10_z)) %>%
    pull(precip_10_med)
  
  temp_30_z_subadult_med = species_data %>%
    filter(life_stage_simple == "subadult") %>%
    summarize(temp_30_med = median(temp_c_30_z)) %>%
    pull(temp_30_med)
  
  # check if at least 1 positive metamorph
  life_stage_counts_positive = species_data %>%
    filter(bd_load_co_density > 0) %>%
    group_by(life_stage_simple) %>%
    count()
  
  # draws for metamorph
  if ("metamorph" %in% life_stage_counts_positive$life_stage_simple) {
    
    # metamorph: svl_mm is irrelevant (smooth is off), use a dummy value
    nd_met <- tibble(
      svl_mm           = mean(species_data$svl_mm, na.rm = TRUE),  # doesn't matter
      is_metamorph     = 1,
      is_not_metamorph = 0,
      precip_mm_10_z  = precip_10_z_subadult_med,
      precip_mm_10_z2 = precip_10_z_subadult_med ^ 2,
      temp_c_30_z     = temp_30_z_subadult_med,
      temp_c_30_z2    = temp_30_z_subadult_med ^ 2
    )
    
    # metamorph
    mu_met      <- nd_met    |> add_epred_draws(species_fit, dpar = "mu",  re_formula = NA)
    
    # metamorph: keep raw draws for boxplot
    mu_met_agg = mu_met |>
      median_qi(mu, .width = c(0.5, 0.95)) |>
      pivot_wider(id_cols = c(svl_mm, mu, is_metamorph),
                  names_from = .width,
                  values_from = c(.lower, .upper))
  } else {
    mu_met_agg = tibble(is_metamorph = 1)
  }
  
  # post-metamorphs
  nd_notmet <- tibble(
    svl_mm          = seq(min(species_data$svl_mm, na.rm = TRUE),
                          max(species_data$svl_mm, na.rm = TRUE),
                          length.out = 200),
    is_metamorph    = 0,
    is_not_metamorph = 1,
    precip_mm_10_z  = precip_10_z_subadult_med,
    precip_mm_10_z2 = precip_10_z_subadult_med ^ 2,
    temp_c_30_z     = temp_30_z_subadult_med,
    temp_c_30_z2    = temp_30_z_subadult_med ^ 2
  )
  
  # non-metamorph
  mu_notmet   <- nd_notmet |> add_epred_draws(species_fit, dpar = "mu",  re_formula = NA)
  
    # non-metamorph: median + interval over svl sequence
  mu_notmet_agg <- mu_notmet |>
    group_by(svl_mm) |>
    median_qi(mu, .width = c(0.5, 0.95)) |>
    pivot_wider(id_cols = c(svl_mm, mu),
                names_from = .width,
                values_from = c(.lower, .upper)) %>%
    mutate(is_metamorph = 0)
    
  mu_agg = bind_rows(mu_met_agg,
                     mu_notmet_agg) %>%
    mutate(taxon_capture = taxon_capture,
           svl_mm_cutoff = cutoff_mm)
  
  return(mu_agg)
}

prev_agg_all = pmap(list(model_list, co_list, taxon_list), metamorph_svl_prev_epred) %>%
  list_rbind()

mu_agg_all = pmap(list(model_list, co_list, taxon_list), metamorph_svl_load_epred) %>%
  list_rbind()

svl_agg_all = prev_agg_all %>%
  left_join(mu_agg_all, by = c("taxon_capture", "is_metamorph", "svl_mm", "svl_mm_cutoff"), suffix = c("_prevalence", "_mu")) %>%
  rename(prevalence_0.5_lower = .lower_0.5_prevalence,
         prevalence_0.5_upper = .upper_0.5_prevalence,
         prevalence_0.95_lower = .lower_0.95_prevalence,
         prevalence_0.95_upper = .upper_0.95_prevalence,
         mu_0.5_lower = .lower_0.5_mu,
         mu_0.5_upper = .upper_0.5_mu,
         mu_0.95_lower = .lower_0.95_mu,
         mu_0.95_upper = .upper_0.95_mu) %>%
  select(taxon_capture,
         is_metamorph,
         svl_mm,
         svl_mm_cutoff,
         everything())

```

## export data to manuscript
```{r}
repo_dir = gsub("size_bd_load_analysis", "", here())
manuscript_data_dir = paste0(repo_dir, "size-bd-dynamics-manuscript/resources/01_essential_data/")

write_parquet(svl_agg_all, paste0(manuscript_data_dir, "GAM_03_a_svl_agg.parquet"))

```

## visualize
```{r}
metamorph_svl_prev_plot = function(svl_agg) {
  all_spp = svl_agg %>%
    select(taxon_capture,
           svl_mm_cutoff) %>%
    distinct() %>%
    arrange(taxon_capture) %>%
    mutate(species_name = gsub("_", "\n", str_to_sentence(taxon_capture)))
  
  prev_range = svl_agg %>%
    summarize(min = min(prevalence_0.95_lower, na.rm = TRUE),
              max = max(prevalence_0.95_upper, na.rm = TRUE))
  
  # preallocate
  plotlist = list()
  
  for (ii in 1:nrow(all_spp)) {
    spp_agg = svl_agg %>%
      filter(taxon_capture == all_spp$taxon_capture[ii])
    
    # --- prevalence ---
    p_prev_met = ggplot(spp_agg %>%
                          filter(is_metamorph == 1), aes(x = "metamorph", lower = prevalence_0.5_lower, upper = prevalence_0.5_upper, middle = prevalence,
                                                         ymin = prevalence_0.95_lower, ymax = prevalence_0.95_upper)) +
      geom_boxplot(stat = "identity", fill = "#8DA0CB", alpha = 0.72, outlier.shape = NA) +
      labs(x = NULL, y = all_spp$species_name[ii]) +
      ylim(prev_range$min, prev_range$max) +
      theme_classic()
    
    p_prev_notmet = ggplot(spp_agg %>%
                             filter(is_metamorph == 0), aes(x = svl_mm, y = prevalence)) +
      geom_ribbon(aes(ymin = prevalence_0.5_lower, ymax = prevalence_0.5_upper), fill = "#8DA0CB", alpha = 0.6) +
      geom_ribbon(aes(ymin = prevalence_0.95_lower, ymax = prevalence_0.95_upper), fill = "#8DA0CB", alpha = 0.3) +
      geom_line(color = "#000", linewidth = 1) +
      geom_vline(xintercept = spp_agg$svl_mm_cutoff[1], linetype = "dashed", color = "#666") +
      labs(x = "SVL (mm)", y = NULL) +
      coord_cartesian(ylim = c(prev_range$min, prev_range$max)) +
      theme_classic() +
      theme(
        axis.text.y  = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y  = element_blank()
      )
    
    p_prev = p_prev_met + p_prev_notmet +
      plot_layout(widths = c(1, 3))
    
    plotlist = c(plotlist,
                 p_prev)
  }
 
  return(plotlist)
}

metamorph_svl_load_plot = function(svl_agg) {
  all_spp = svl_agg %>%
    select(taxon_capture,
           svl_mm_cutoff) %>%
    distinct() %>%
    arrange(taxon_capture) %>%
    mutate(species_name = gsub("_", "\n", str_to_sentence(taxon_capture)))
  
  load_range = svl_agg %>%
    filter(is_metamorph == 0) %>%
    summarize(min = min(mu_0.5_lower, na.rm = TRUE),
              max = max(mu_0.5_upper, na.rm = TRUE))
  
  # preallocate
  plotlist = list()
  
  for (ii in 1:nrow(all_spp)) {
    spp_agg = svl_agg %>%
      filter(taxon_capture == all_spp$taxon_capture[ii])
    
    # --- load ---
    p_mu_met = ggplot(spp_agg %>%
                          filter(is_metamorph == 1),
                        aes(x = "metamorph", lower = mu_0.5_lower, upper = mu_0.5_upper, middle = mu,
                            ymin = mu_0.95_lower, ymax = mu_0.95_upper)) +
      geom_boxplot(stat = "identity", fill = "#FC8D62", alpha = 0.72, outlier.shape = NA) +
      labs(x = NULL, y = all_spp$species_name[ii]) +
      coord_cartesian(ylim = c(load_range$min, load_range$max)) +
      theme_classic()
    
    p_mu_notmet = ggplot(spp_agg %>%
                             filter(is_metamorph == 0), aes(x = svl_mm, y = mu)) +
      geom_ribbon(aes(ymin = mu_0.5_lower, ymax = mu_0.5_upper), fill = "#FC8D62", alpha = 0.6) +
      geom_ribbon(aes(ymin = mu_0.95_lower, ymax = mu_0.95_upper), fill = "#FC8D62", alpha = 0.3) +
      geom_line(color = "#000", linewidth = 1) +
      geom_vline(xintercept = spp_agg$svl_mm_cutoff[1], linetype = "dashed", color = "#666") +
      labs(x = "SVL (mm)", y = NULL) +
      coord_cartesian(ylim = c(load_range$min, load_range$max)) +
      theme_classic() +
      theme(
        axis.text.y  = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y  = element_blank()
      )
    
    p_mu = p_mu_met + p_mu_notmet +
      plot_layout(widths = c(1, 3))
    
    plotlist = c(plotlist,
                 p_mu)
  }
 
  return(plotlist)
}

prev_plot_list = metamorph_svl_prev_plot(svl_agg_all)
load_plot_list = metamorph_svl_load_plot(svl_agg_all)

ylab_dummy_prev = ggplot() + 
  annotate("text", x = 0.5, y = 0.5, label = "Bd prevalence", angle = 90, size = 5) +
  theme_void() +
  coord_fixed(ratio = 10)

ylab_dummy_load = ggplot() + 
  annotate("text", x = 0.5, y = 0.5, label = "log(Bd load)", angle = 90, size = 5) +
  theme_void() +
  coord_fixed(ratio = 10)

p_prev = (ylab_dummy_prev + wrap_plots(prev_plot_list, nrow = length(taxon_list))) +
  plot_layout(widths = c(0.05, 1))

p_load = (ylab_dummy_load + wrap_plots(load_plot_list, nrow = length(taxon_list))) +
  plot_layout(widths = c(0.05, 1))

ggsave(here("size_bd_gam", "gam_figures", "03_metamorph_svl_combined_m3_prevalence.png"),
       p_prev,
       width = 8, height = length(taxon_list) * 2)

ggsave(here("size_bd_gam", "gam_figures", "03_metamorph_svl_combined_m3_load.png"),
       p_load,
       width = 8, height = length(taxon_list) * 2)

p_prev
p_load

```

# Recreate groups
```{r}
hu_draws_groups = hu_draws %>%
  mutate(life_stage_simple = case_when(
    taxon_capture == "rana_cascadae" & svl_mm >= 50 ~ "adult",
    taxon_capture == "rana_cascadae" & svl_mm < 50 ~ "subadult",
    taxon_capture %in% c("rana_muscosa", "rana_sierrae") & svl_mm >= 40 ~ "adult",
    taxon_capture %in% c("rana_muscosa", "rana_sierrae") & svl_mm < 40 ~ "subadult"
  ))

mu_draws_groups = mu_draws %>%
  mutate(life_stage_simple = case_when(
    taxon_capture == "rana_cascadae" & svl_mm >= 50 ~ "adult",
    taxon_capture == "rana_cascadae" & svl_mm < 50 ~ "subadult",
    taxon_capture %in% c("rana_muscosa", "rana_sierrae") & svl_mm >= 40 ~ "adult",
    taxon_capture %in% c("rana_muscosa", "rana_sierrae") & svl_mm < 40 ~ "subadult"
  ))

hu_groups_agg = hu_draws_groups %>%
  group_by(taxon_capture, life_stage_simple) %>%
  median_qi(hu, .width = c(.89))

mu_groups_agg = mu_draws_groups %>%
  group_by(taxon_capture, life_stage_simple) %>%
  median_qi(mu, .width = c(.89))


```