---
title: "Size vs. Bd modeling"
author: Cob Staines
---

## Setup
```{r}
#| eval: true
#| output: false
#| code-fold: true
#| code-summary: "Show setup code"

# setup
librarian::shelf(tidyverse, here, janitor, brms, tidybayes, bayesplot, stan-dev/cmdstanr, bayestestR, terra)

```


## Load saved data
```{r}
#| eval: true
#| warning: false
#| echo: false
#| code-fold: true
#| code-summary: "Show data loading code"

# load bd_model_env
load(here("size_bd_unified", "intermediates", "bd_model_env_unified_2026-04-22.RData"))

brms_data = brms_data %>%
  mutate(population = if_else(population == "Santa Virginia", "santa_virginia", population))

# checks
sum(is.na(brms_data$bd_load_co_density))
sum(is.na(brms_data$precip_mm_30_day_sum))
sum(is.na(brms_data$temperature_max_c))
sum(is.na(brms_data$past_year_weekly_precipitation_mm_sd))
sum(is.na(brms_data$past_year_weekly_tempurature_max_c_sd))

bd_model_env_stats = brms_data %>%
  group_by(taxon_capture, country) %>%
  summarise(regions = paste(sort(unique(region)), collapse = ", "),
            population_n = n_distinct(population),
            site_n = n_distinct(site),
            year_first = year(min(date)),
            year_last = year(max(date)),
            year_count = n_distinct(year(date)),
            adult_n = sum(life_stage_simple == "adult"),
            adult_n_pos = sum(life_stage_simple == "adult" & bd_detected_co),
            subadult_n = sum(life_stage_simple == "subadult"),
            subadult_n_pos = sum(life_stage_simple == "subadult" & bd_detected_co),
            .groups = "drop") %>%
  arrange(country,
          taxon_capture)

## KG zones
kg_key = read_csv(here("data", "koppen_geiger_tif", "legend.csv")) %>%
  select(-rgb) %>%
  rename_with(function(x) { paste0("kg_", x) })

all_sites = brms_data %>%
  group_by(site, population, country) %>%
  summarize(site_latitude = mean(site_latitude),
            site_longitude = mean(site_longitude),
            taxa = paste0(sort(unique(taxon_capture)), collapse = ", "),
            taxa_n = n_distinct(taxon_capture),
            adult_n = sum(life_stage_simple == "adult"),
            subadult_n = sum(life_stage_simple == "subadult"),
            .groups = "drop")

site_coords = cbind(lon = all_sites$site_longitude,
                    lat = all_sites$site_latitude)

kg_rast = rast(here("data", "koppen_geiger_tif", "1991_2020", "koppen_geiger_0p00833333.tif"))

kg_extract = extract(kg_rast, site_coords) %>%
  dplyr::rename(kg_id = koppen_geiger_0p00833333) %>%
  mutate(kg_id = if_else(kg_id == 29, 19, kg_id))

all_sites_kg = bind_cols(all_sites,
                          kg_extract) %>%
  left_join(kg_key, by = "kg_id")

brms_data = brms_data %>%
  dplyr::select(-site_latitude,
                -site_longitude) %>%
  left_join(all_sites_kg %>%
  dplyr::select(site,
                site_latitude,
                site_longitude,
                kg_code_1,
                kg_code_2,
                kg_code_3), by = "site")

peace = get_dupes(all_sites_kg, site)

# cluster means
mmode = function(x) {
  ux = unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

brms_data = brms_data %>%
  group_by(taxon_capture) %>%
  mutate(precip_mm_10_cm = mean(precip_mm_10_z),
         temp_c_30_cm = mean(temp_c_30_z),
         kg_code_3_cm = mmode(kg_code_3)) %>%
  ungroup

# save(brms_data, file = "/home/cob/Documents/ribbitr/repos/r-brms-contained/data/bd_model_env_unified_2026-04-22.RData")

```

# visualize
```{r}
ggplot(all_sites_kg, aes(x = kg_code_2, fill = kg_code_3)) +
  geom_bar() +
  scale_y_log10()

ggplot(brms_data, aes(x = kg_code_3)) +
  geom_bar()

ggplot(brms_data, aes(x = precip_mm_10_cm)) +
  geom_bar() +
  scale_y_log10()

ggplot(brms_data, aes(x = precip_mm_10_day_sum, fill = taxon_capture)) +
  geom_histogram() +
  scale_x_log10()

ggplot(brms_data, aes(x = temp_c_30_day_mean, fill = taxon_capture)) +
  geom_histogram()

```

# Modeling

## Model setup
```{r}
#| code-fold: true
#| code-summary: "Show model setup code"

set_cmdstan_path(Sys.getenv("cmd_stan_path"))

model_priors <- c(
  # b
  prior(normal(5, 4), class = "Intercept"),
  prior(normal(0, 3),   class = "b"),
  
  # hu
  prior(normal(0, 2), class = "Intercept", dpar = "hu"),
  prior(normal(0, 2), class = "b", dpar = "hu"),
  
  # Sigma
  prior(normal(0, 1), class = "Intercept", dpar = "sigma"),
  prior(normal(0, 0.3), class = "b", dpar = "sigma"),
  
  # Random effects
  prior(exponential(1), class = "sd")
)

# model_priors_ga <- c(
#   # b
#   prior(normal(0, 5), class = "Intercept"),
#   prior(normal(0, 3),   class = "link"),
#   
#   # hu
#   prior(normal(0, 2), class = "Intercept", dpar = "link_hu"),
#   prior(normal(0, 1), class = "b", dpar = "link_hu"),
#   
#   # Sigma
#   prior(normal(0, 1), class = "Intercept", dpar = "link_shape"),
#   prior(normal(0, 0.3), class = "b", dpar = "link_shape"),
#   
#   # Random effects
#   prior(exponential(1), class = "sd")
# )
# 
# model_priors_fixed <- c(
#   # b
#   prior(normal(0, 5), class = "Intercept"),
#   prior(normal(0, 3),   class = "b"),
#   
#   # hu
#   prior(normal(0, 2), class = "Intercept", dpar = "hu"),
#   prior(normal(0, 1), class = "b", dpar = "hu"),
#   
#   # Sigma
#   prior(normal(0, 1), class = "Intercept", dpar = "sigma"),
#   prior(normal(0, 0.3), class = "b", dpar = "sigma")
# )

```

## Model fitting
```{r}
#| eval: false
#| code-fold: true
#| code-summary: "Show model fitting code"

null_zln <- brm(
  bd_load_co_density ~ 1,
  data = brms_data,
  family = hurdle_lognormal(),
  control = list(adapt_delta = 0.95, max_treedepth = 12),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 124,
  cores = 4,
  backend = "cmdstanr"
)

null_zln <- add_criterion(null_zln, "loo")

saveRDS(null_zln, file = here("size_bd_unified/unified_models/unified_model_results_zln_null.rds"))
null_zln = readRDS(file = here("size_bd_unified/unified_models/unified_model_results_zln_null.rds"))
# 
# nullb_zln <- brm(
#   bd_load_co ~ 1,
#   data = brms_data,
#   family = hurdle_lognormal(),
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# nullb_zln <- add_criterion(nullb_zln, "loo")
# 
# saveRDS(nullb_zln, file = here("unified_models/unified_model_results_zln_nullb.rds"))
# nullb_zln = readRDS(file = here("unified_models/unified_model_results_zln_nullb.rds"))
# 
# m1_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture,
#     hu ~ 1 + life_stage_simple * taxon_capture,
#     sigma ~ 1 + taxon_capture
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors_fixed,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m1_zln <- add_criterion(m1_zln, "loo")
# 
# saveRDS(m1_zln, file = here("unified_models/unified_model_results_zln_life_tax.rds"))
# m1_zln = readRDS(file = here("unified_models/unified_model_results_zln_life_tax.rds"))
# 

# m2_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + (1 | population),
#     hu ~ 1 + life_stage_simple * taxon_capture + (1 | population),
#     sigma ~ 1 + taxon_capture
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m2_zln <- add_criterion(m2_zln, "loo")
# 
# saveRDS(m2_zln, file = here("unified_models/unified_model_results_zln_life_tax_pop.rds"))
# m2_zln = readRDS(file = here("unified_models/unified_model_results_zln_life_tax_pop.rds"))
# 
# m2b_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + (1 | population),
#     hu ~ 1 + life_stage_simple * taxon_capture + (1 | population),
#     sigma ~ 1 + taxon_capture + (1 | population)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m2b_zln <- add_criterion(m2b_zln, "loo")
# 
# saveRDS(m2b_zln, file = here("unified_models/unified_model_results_zln_life_tax_popb.rds"))
# m2b_zln = readRDS(file = here("unified_models/unified_model_results_zln_life_tax_popb.rds"))

# m2b_zga <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + (1 | population),
#     hu ~ 1 + life_stage_simple * taxon_capture + (1 | population),
#     shape ~ 1 + taxon_capture + (1 | population)
#   ),
#   data = brms_data,
#   family = hurdle_gamma(),
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m2b_zga <- add_criterion(m2b_zga, "loo")
# 
# saveRDS(m2b_zga, file = here("unified_models/unified_model_results_zga_life_tax_popb.rds"))
# m2b_zga = readRDS(file = here("unified_models/unified_model_results_zga_life_tax_popb.rds"))
# 
# m3_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + (1 + population) +  (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + (1 + population) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture + (1 + population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m3_zln <- add_criterion(m3_zln, "loo")
# 
# saveRDS(m3_zln, file = here("unified_models/unified_model_results_zln_life_tax_poptls.rds"))
# m3_zln = readRDS(file = here("unified_models/unified_model_results_zln_life_tax_poptls.rds"))
# 
# m3b_zln <- brm(
#   formula = bf(
#     bd_load_co ~ 1 + life_stage_simple * taxon_capture + (1 + population) +  (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + (1 + population) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture + (1 + population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m3b_zln <- add_criterion(m3b_zln, "loo")
# 
# saveRDS(m3b_zln, file = here("unified_models/unified_model_results_zln_life_tax_poptls_nodens.rds"))
# m3b_zln = readRDS(file = here("unified_models/unified_model_results_zln_life_tax_poptls_nodens.rds"))

# m4_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_z + temp_c_30_z + (1 + population) +  (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_z + temp_c_15_z + (1 + population) +  (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture + (1 + population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# m4_zln <- add_criterion(m4_zln, "loo")
# 
# saveRDS(m4_zln, file = "unified_models/unified_model_results_zln_life_tax_pop_env.rds")
# m4_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pop_env.rds")
# 
# m5_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 | population) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 + (1 | population) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m5_zln <- add_criterion(m5_zln, "loo")
# 
# saveRDS(m5_zln, file = "unified_models/unified_model_results_zln_life_tax_poptls_env2.rds")
# m5_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls_env2.rds")
# 

# m5b_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 | population) + (1 + precip_mm_30_z + temp_c_30_z | taxon_capture) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 + (1 | population) + (1 + precip_mm_15_z + temp_c_15_z | taxon_capture) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m5b_zln <- add_criterion(m5b_zln, "loo")
# 
# saveRDS(m5b_zln, file = "unified_models/unified_model_results_zln_life_tax_poptlsenv_env2.rds")
# m5b_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptlsenv_env2.rds")
# 
# m5c_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 | population) + (1 + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 | taxon_capture) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 + (1 | population) + (1 + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 | taxon_capture) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m5c_zln <- add_criterion(m5c_zln, "loo")
# 
# saveRDS(m5c_zln, file = "unified_models/unified_model_results_zln_life_tax_poptlsenv2_env2.rds")
# m5c_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptlsenv2_env2.rds")

# m5d_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 | population) + (1 + precip_mm_30_z + temp_c_30_z | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 + (1 | population) + (1 + precip_mm_15_z + temp_c_15_z | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m5d_zln <- add_criterion(m5d_zln, "loo")
# 
# saveRDS(m5d_zln, file = "unified_models/unified_model_results_zln_life_tax_poptls2env_env2.rds")
# m5d_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls2env_env2.rds")


# m5e_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 | population) + (1 + precip_mm_30_z + temp_c_30_z | taxon_capture) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 + (1 | population) + (1 + precip_mm_15_z + temp_c_15_z | taxon_capture) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + life_stage_simple * taxon_capture +  (1 | population) + (1 | population:taxon_capture:life_stage_simple)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m5e_zln <- add_criterion(m5e_zln, "loo")
# 
# saveRDS(m5e_zln, file = "unified_models/unified_model_results_zln_life_tax_poptlsenv_env2_sigls.rds")
# m5e_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptlsenv_env2_sigls.rds")
# 
# m5f_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 | population) + (1 + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 + (1 | population) + (1 + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m5f_zln <- add_criterion(m5f_zln, "loo")
# 
# saveRDS(m5f_zln, file = "unified_models/unified_model_results_zln_life_tax_poptls2env2_env2.rds")
# m5f_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls2env2_env2.rds")

##
## I think I should drop the (1|population) terms and keep only the (1|population:taxon_capture:life_stage_simple) terms... maybe? Or does the fact that they are not neatly nested mean this not trully redundant?
##
##
# m5g_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + (1 | population) + (1 + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + (1 | population) + (1 + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m5g_zln <- add_criterion(m5g_zln, "loo")
# 
# saveRDS(m5g_zln, file = "unified_models/unified_model_results_zln_life_tax_poptls2env2_30.rds")
# m5g_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls2env2_30.rds")
# 
# m6_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 + (1 | population) + (1 + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_sp_z + precip_mm_15_sp_z2 + temp_c_15_sp_z + temp_c_15_sp_z2 + (1 | population) + (1 + precip_mm_15_sp_z + precip_mm_15_sp_z2 + temp_c_15_sp_z + temp_c_15_sp_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m6_zln <- add_criterion(m6_zln, "loo")
# 
# saveRDS(m6_zln, file = "unified_models/unified_model_results_zln_life_tax_poptls2envsp2_envsp2.rds")
# m6_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls2envsp2_envsp2.rds")
# 
# m6b_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + (1 | population) + (1 + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 | taxon_capture) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + (1 | population) + (1 + precip_mm_15_sp_z + precip_mm_15_sp_z2 + temp_c_15_sp_z + temp_c_15_sp_z2 | taxon_capture) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m6b_zln <- add_criterion(m6b_zln, "loo")
# 
# saveRDS(m6b_zln, file = "unified_models/unified_model_results_zln_life_tax_popt2envsp2.rds")
# m6b_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_popt2envsp2.rds")
# 
# m6c_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 + (1 | population) + (1 + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 + (1 | population) + (1 + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m6c_zln <- add_criterion(m6c_zln, "loo")
# 
# saveRDS(m6c_zln, file = "unified_models/unified_model_results_zln_life_tax_poptls2envsp2_envsp2_30.rds")
# m6c_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls2envsp2_envsp2_30.rds")
# 
# m6d_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + (1 | population) + (1 + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + (1 | population) + (1 + precip_mm_30_sp_z + precip_mm_30_sp_z2 + temp_c_30_sp_z + temp_c_30_sp_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m6d_zln <- add_criterion(m6d_zln, "loo")
# 
# saveRDS(m6d_zln, file = "unified_models/unified_model_results_zln_life_tax_poptls2envsp2_30.rds")
# m6d_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls2envsp2_30.rds")
# 
# m7_zln <- brm(
#   formula = bf(
#     bd_load_co ~ 1 + life_stage_simple * taxon_capture + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 + (1 | population) + (1 + precip_mm_30_z + precip_mm_30_z2 + temp_c_30_z + temp_c_30_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 + (1 | population) + (1 + precip_mm_15_z + precip_mm_15_z2 + temp_c_15_z + temp_c_15_z2 | taxon_capture:life_stage_simple) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.95, max_treedepth = 12),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 124,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m7_zln <- add_criterion(m7_zln, "loo")
# 
# saveRDS(m7_zln, file = "unified_models/unified_model_results_zln_life_tax_poptls2env2_env2_nodens.rds")
# m7_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls2env2_env2_nodens.rds")
# 

# m8_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + life_stage_simple * taxon_capture + (precip_mm_10_z + I(precip_mm_10_z^2) + temp_c_30_z + I(temp_c_30_z^2)) * taxon_capture + (1 | population) + (1 | population:taxon_capture:life_stage_simple),
#     hu ~ 1 + life_stage_simple * taxon_capture + (precip_mm_10_z + I(precip_mm_10_z^2) + temp_c_30_z + I(temp_c_30_z^2)) * taxon_capture + (1 | population) + (1 | population:taxon_capture:life_stage_simple),
#     sigma ~ 1 + taxon_capture +  (1 | population) + (1 | population:taxon_capture)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.98),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 125,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m8_zln <- add_criterion(m8_zln, "loo")
# 
# saveRDS(m8_zln, file = "unified_models/unified_model_results_zln_life_tax_env2_rpoptls_p10t30.rds")
# m8_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_env2_rpoptls_p10t30.rds")

# quadratic fixed temp and precip, linear random
m9a_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + I(precip_mm_10_z^2) + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z | taxon_capture) +
      (1 | population) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + I(precip_mm_10_z^2) + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z | taxon_capture) +
      (1 | population) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 125,
  cores = 4,
  backend = "cmdstanr"
)

m9a_zln <- add_criterion(m9a_zln, "loo")

saveRDS(m9a_zln, file = "unified_models/unified_model_results_zln_life_tax_env2_renvpoptls_p10t30.rds")
m9a_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_env2_renvpoptls_p10t30.rds")

# quadratic fixed and random temp and precip
m9b_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + I(precip_mm_10_z^2) + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + I(precip_mm_10_z^2) + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + I(precip_mm_10_z^2) + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + I(precip_mm_10_z^2) + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 125,
  cores = 4,
  backend = "cmdstanr"
)

m9b_zln <- add_criterion(m9b_zln, "loo")

saveRDS(m9b_zln, file = "unified_models/unified_model_results_zln_life_tax_env2_renv2poptls_p10t30.rds")
m9b_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_env2_renv2poptls_p10t30.rds")

# # 30-day precip lag
# m9b_30_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + 
#       life_stage_simple * taxon_capture +
#       (precip_mm_30_z + I(precip_mm_30_z^2) + temp_c_30_z + I(temp_c_30_z^2)) +
#       (0 + precip_mm_30_z + I(precip_mm_30_z^2) + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
#       (1 | population) + 
#       (1 | population:taxon_capture:life_stage_simple),
#     
#     hu ~ 1 + 
#       life_stage_simple * taxon_capture +
#       (precip_mm_30_z + I(precip_mm_30_z^2) + temp_c_30_z + I(temp_c_30_z^2)) +
#       (0 + precip_mm_30_z + I(precip_mm_30_z^2) + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
#       (1 | population) + 
#       (1 | population:taxon_capture:life_stage_simple),
#     
#     sigma ~ 1 + taxon_capture + 
#       (1 | population)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.98),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 125,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m9b_30_zln <- add_criterion(m9b_30_zln, "loo")
# 
# saveRDS(m9b_30_zln, file = "unified_models/unified_model_results_zln_life_tax_env2_renv2poptls_p30t30.rds")
# m9b_30_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_env2_renv2poptls_p30t30.rds")

# quadratic in temp, linear in precip
m9c_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 125,
  cores = 4,
  backend = "cmdstanr"
)

m9c_zln <- add_criterion(m9c_zln, "loo")

saveRDS(m9c_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptls_p10t30.rds")
m9c_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptls_p10t30.rds")

# quadratic temp, linear precip, year
m9d_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population:year)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 125,
  cores = 4,
  backend = "cmdstanr"
)

m9d_zln <- add_criterion(m9d_zln, "loo")

saveRDS(m9d_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyr_p10t30.rds")
m9d_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyr_p10t30.rds")

# quadratic temp, linear precip, year, nested taxon random
m9e_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population:year) + 
      (1 | taxon_capture/population:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population:year) + 
      (1 | taxon_capture/population:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population:year)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 125,
  cores = 4,
  backend = "cmdstanr"
)

m9e_zln <- add_criterion(m9e_zln, "loo")

saveRDS(m9e_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2popt*lsyr_p10t30.rds")
m9e_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2popt*lsyr_p10t30.rds")

# quadratic temp, linear precip, year, temp var linear
m9f_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      past_year_weekly_tempurature_max_c_sd +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      past_year_weekly_tempurature_max_c_sd +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population:year)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m9f_zln <- add_criterion(m9f_zln, "loo")

saveRDS(m9f_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrclt_p10t30.rds")
m9f_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrclt_p10t30.rds")

# quadratic temp, linear precip, year, precip var linear
m9g_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      past_year_weekly_precipitation_mm_sd +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      past_year_weekly_precipitation_mm_sd +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population:year)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m9g_zln <- add_criterion(m9g_zln, "loo")

saveRDS(m9g_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrclp_p10t30.rds")
m9g_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrclp_p10t30.rds")

# quadratic temp, linear precip, year, precip var linear
m9h_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_2) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_2) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population:year)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m9h_zln <- add_criterion(m9h_zln, "loo")

saveRDS(m9h_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrkg2_p10t30.rds")
m9h_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrkg2_p10t30.rds")

# quadratic temp, linear precip, year, precip var linear
m9i_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | population:year) + 
      (1 | population:taxon_capture:life_stage_simple),
    
    sigma ~ 1 + taxon_capture + 
      (1 | population:year)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m9i_zln <- add_criterion(m9i_zln, "loo")

saveRDS(m9i_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrkg3_p10t30.rds")
m9i_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrkg3_p10t30.rds")
# 
# # quadratic temp, linear precip, year, precip var linear, random effects of year with life_stage_simple
# m10a_zln <- brm(
#   formula = bf(
#     bd_load_co_density ~ 1 + 
#       life_stage_simple * taxon_capture +
#       (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
#       (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
#       (1 | kg_code_3) +
#       (1 | population) +
#       (1 | population:taxon_capture:life_stage_simple) +
#       (0 + life_stage_simple || population:taxon_capture:year),
#     
#     hu ~ 1 + 
#       life_stage_simple * taxon_capture +
#       (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
#       (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
#       (1 | kg_code_3) +
#       (1 | population) +
#       (1 | population:taxon_capture:life_stage_simple) +
#       (0 + life_stage_simple || population:taxon_capture:year),
#     
#     sigma ~ 1 + taxon_capture + 
#       (1 | population:year)
#   ),
#   data = brms_data,
#   family = hurdle_lognormal(),
#   prior = model_priors,
#   sample_prior = "yes",
#   control = list(adapt_delta = 0.98),
#   chains = 4,
#   iter = 2000,
#   warmup = 1000,
#   seed = 126,
#   cores = 4,
#   backend = "cmdstanr"
# )
# 
# m10a_zln <- add_criterion(m10a_zln, "loo")
# 
# saveRDS(m10a_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrkg3ls_p10t30.rds")
# m10a_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rpt2poptlsyrkg3ls_p10t30.rds")

# isolate scales between taxa
m10b_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | population:taxon_capture:life_stage_simple) +
      (0 + life_stage_simple || population:taxon_capture:year),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | population:taxon_capture:life_stage_simple) +
      (0 + life_stage_simple || population:taxon_capture:year),
    
    sigma ~ 1 + taxon_capture
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m10b_zln <- add_criterion(m10b_zln, "loo", moment_match = TRUE)

saveRDS(m10b_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rtaxapt2poplsyrkg3_p10t30.rds")
m10b_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rtaxapt2poplsyrkg3_p10t30.rds")

# isolate scales between taxa
m11a_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple || gr(taxon_capture:population:year, by = taxon_capture)),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple || gr(taxon_capture:population:year, by = taxon_capture)),
    
    sigma ~ 1 + taxon_capture + (1 | taxon_capture:population)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m11a_zln <- add_criterion(m11a_zln, "loo", moment_match = TRUE)

saveRDS(m11a_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxapt2poplsyrkg3_p10t30.rds")
m11a_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxapt2poplsyrkg3_p10t30.rds")

# isolate scales between taxa
m11b_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    sigma ~ 1 + taxon_capture + (1 | taxon_capture:population)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m11b_zln <- add_criterion(m11b_zln, "loo")

saveRDS(m11b_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3_p10t30.rds")
m11b_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3_p10t30.rds")

# simpler sigma effects
m11c_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    sigma ~ 1 + taxon_capture
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m11c_zln <- add_criterion(m11c_zln, "loo", moment_match = TRUE)

saveRDS(m11c_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3_sigtax_p10t30_20260514_034956.rds")
m11c_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3_sigtax_p10t30_20260514_034956.rds")

# group sigma random effects by taxon
m11d_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    sigma ~ 1 + taxon_capture + (1 | gr(taxon_capture:population), by = taxon_capture)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m11d_zln <- add_criterion(m11d_zln, "loo")

saveRDS(m11d_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3_sigtaxrpop_p10t30_20260516_145515.rds")
m11d_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3_sigtaxrpop_p10t30_20260516_145515.rds")

# simpler kg in sigma effects
m11e_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z  + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      (precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2)) +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    sigma ~ 1 + taxon_capture + (1 | taxon_capture:population) + (1 | kg_code_3)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m11e_zln <- add_criterion(m11e_zln, "loo")

saveRDS(m11e_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3_sigma_taxpopkg_p10t30.rds")
m11e_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3__sigma_taxpopkg_p10t30.rds")

# include taxon center means for temp, precip and climate zones
m12a_zln <- brm(
  formula = bf(
    bd_load_co_density ~ 1 + 
      life_stage_simple * taxon_capture +
      temp_c_30_cm + temp_c_30_z + I(temp_c_30_z^2) +
      precip_mm_10_cm + precip_mm_10_z +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      kg_code_3_cm + (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    hu ~ 1 + 
      life_stage_simple * taxon_capture +
      temp_c_30_cm + temp_c_30_z + I(temp_c_30_z^2) +
      precip_mm_10_cm + precip_mm_10_z +
      (0 + precip_mm_10_z + temp_c_30_z + I(temp_c_30_z^2) | taxon_capture) +
      kg_code_3_cm + (1 | kg_code_3) +
      (1 | gr(taxon_capture:population:life_stage_simple, by = taxon_capture)) +
      (0 + life_stage_simple | gr(taxon_capture:population:year, by = taxon_capture)),
    
    sigma ~ 1 + taxon_capture + (1 | taxon_capture:population)
  ),
  data = brms_data,
  family = hurdle_lognormal(),
  prior = model_priors,
  sample_prior = "yes",
  control = list(adapt_delta = 0.98),
  chains = 4,
  iter = 2000,
  warmup = 1000,
  seed = 126,
  cores = 4,
  backend = "cmdstanr"
)

m12a_zln <- add_criterion(m12a_zln, "loo")

saveRDS(m12a_zln, file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3cm_p10t30.rds")
m12a_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_pt2_rgrtaxacorpt2poplsyrkg3cm_p10t30.rds")

```

## Model comparison
```{r}
#| eval: false
#| code-fold: true
#| code-summary: "Show model comparison code"
# model comparison and selection

(loo_comp_out = loo_compare(null_zln,
                            # # nullb_zln, # no density
                            # # m1_zln,
                            # # m2_zln,
                            # # m2b_zln,
                            # # m3_zln,
                            # # m3b_zln,  # no density
                            # # m4_zln,
                            # # m5_zln,
                            # # m5b_zln,
                            # # m5c_zln,
                            # # m5d_zln,
                            # # m5e_zln,
                            # # m5f_zln,
                            # # m5g_zln
                            # # m6_zln,
                            # # m6b_zln,
                            # # m6c_zln,
                            # # m6d_zln,
                            # # m8_zln,
                            m9a_zln,
                            m9b_zln,
                            # # m9b_30_zln
                            m9c_zln,
                            m9d_zln,
                            m9e_zln,
                            m9f_zln,
                            m9g_zln,
                            m9h_zln,
                            m9i_zln,
                            m10b_zln,
                            m11a_zln,
                            m11b_zln,
                            m11c_zln,
                            m11d_zln
                            ))
```


## Model checks

### Fitting and correlation checks
```{r}
#| eval: true
#| code-fold: true
#| code-summary: "Show model checks code"
#| fig-height: 6
#| fig-width: 8

model_select = m11b_zln

summary(model_select)
plot((model_select), ask = FALSE)
plot(conditional_effects(model_select), ask = FALSE)
VarCorr(model_select)
bayes_R2(model_select)
```

# convergence comparison
```{r}
# For one model (e.g., m11b_zln)
diag1 <- as_draws_df(m11a_zln) |> 
  summarize_draws("rhat", "ess_bulk", "ess_tail") |> 
  mutate(Model = "m11a_zln")

# For second model (e.g., m12)
diag2 <- as_draws_df(m11b_zln) |> 
  summarize_draws("rhat", "ess_bulk", "ess_tail") |> 
  mutate(odel = "m11b_zln")

# Combine and summarize issues
diag_combined <- bind_rows(diag1, diag2)

# Flag problems
peace = diag_combined |>
  pivot_wider(id_cols = "variable",
              names_from = "Model",
              values_from = c("rhat",
                              "ess_bulk",
                              "ess_tail")) %>%
  filter(rhat_m11a_zln > 1.01 |
           rhat_m11b_zln > 1.01)

ggplot(peace, aes(x = rhat_m11a_zln, y = rhat_m11b_zln)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)

```

### Posterios predictive checks
```{r}
#| eval: true
#| code-fold: true
#| code-summary: "Show model checks code (fixed effects)"
#| fig-height: 10
#| fig-width: 10

color_scheme_set("viridis")
# model_select = m5g_zln


pp_check(model_select,
         type = "dens_overlay",
         prefix = "ppc",
         ndraws = 100) +
  scale_x_log10()

# # break out by taxon
# pp_check(model_select,
#          type = "dens_overlay_grouped",
#          group = "taxon_capture",
#          ndraws = 100) +
#   scale_x_log10()

spp_pp_check = pp_check(model_select, group = "taxon_capture", type = "dens_overlay_grouped") +
  scale_x_log10()

spp_pp_check + 
  ylim(0, .5)

```

### Prior checks
```{r}
#| eval: false
#| code-fold: true
#| code-summary: "Show prior checks code"
#| fig-height: 6
#| fig-width: 8

mcmc_plot(model_select, type = "dens", variable = c("prior_Intercept", "b_Intercept")) +
  xlim(-20, 20)

# mcmc_plot(m5f_zln, type = "dens", variable = c("prior_b", "b_taxon_capturecolostethus_panamansis", "b_taxon_capturelithobates_blairi", 
# "b_taxon_capturelithobates_sphenocephalus", "b_taxon_capturelithobates_warszewitschii", 
# "b_taxon_capturepseudacris_crucifer", "b_taxon_capturerana_catesbeiana", 
# "b_taxon_capturerana_clamitans", "b_taxon_capturerana_muscosa", 
# "b_taxon_capturerana_pipiens", "b_taxon_capturerana_sierrae", 
# "b_taxon_capturesilverstoneia_flotator")) +
#   xlim(-10, 10)

mcmc_plot(model_select, type = "dens", variable = c("prior_Intercept_sigma", "b_sigma_Intercept")) +
  xlim(-2, 2)

# mcmc_plot(m5f_zln, type = "dens", variable = c("prior_b_sigma", "b_sigma_taxon_capturecolostethus_panamansis", "b_sigma_taxon_capturelithobates_blairi", 
# "b_sigma_taxon_capturelithobates_sphenocephalus", "b_sigma_taxon_capturelithobates_warszewitschii", 
# "b_sigma_taxon_capturepseudacris_crucifer", "b_sigma_taxon_capturerana_catesbeiana", 
# "b_sigma_taxon_capturerana_clamitans", "b_sigma_taxon_capturerana_muscosa", 
# "b_sigma_taxon_capturerana_pipiens", "b_sigma_taxon_capturerana_sierrae", 
# "b_sigma_taxon_capturesilverstoneia_flotator")) +
#   xlim(-2, 2)

mcmc_plot(model_select, type = "dens", variable = c("prior_Intercept_hu", "b_hu_Intercept")) +
  xlim(-15, 15)

# mcmc_plot(m5f_zln, type = "dens", variable = c("prior_b_hu", "b_hu_life_stage_simplesubadult", "b_hu_taxon_capturecolostethus_panamansis", 
# "b_hu_taxon_capturelithobates_blairi", "b_hu_taxon_capturelithobates_sphenocephalus", 
# "b_hu_taxon_capturelithobates_warszewitschii", "b_hu_taxon_capturepseudacris_crucifer", 
# "b_hu_taxon_capturerana_catesbeiana", "b_hu_taxon_capturerana_clamitans", 
# "b_hu_taxon_capturerana_muscosa", "b_hu_taxon_capturerana_pipiens", 
# "b_hu_taxon_capturerana_sierrae", "b_hu_taxon_capturesilverstoneia_flotator")) +
#   xlim(-5, 5)

```

# climate model draws
```{r}
get_variables(mxf_zln)

summary(mxf_zln)
plot(mxf_zln)

mxf_draws = mxf_zln %>%
  spread_draws(`.*past_year_weekly.*`, regex = TRUE) %>%
  filter(.chain != 1)


ggplot(mxf_draws, aes(x = b_past_year_weekly_tempurature_max_c_sd)) +
  geom_histogram()

ggplot(mxf_draws, aes(x = b_past_year_weekly_precipitation_mm_sd)) +
  geom_histogram()

ggplot(mxf_draws, aes(x = b_hu_past_year_weekly_tempurature_max_c_sd)) +
  geom_histogram()

ggplot(mxf_draws, aes(x = b_hu_past_year_weekly_precipitation_mm_sd)) +
  geom_histogram()

ggplot(mxf_draws, aes(x = b_sigma_past_year_weekly_tempurature_max_c_sd)) +
  geom_histogram()

ggplot(mxf_draws, aes(x = b_sigma_past_year_weekly_precipitation_mm_sd)) +
  geom_histogram()
  


# hu contrast
hu_spp_lss_draws = model_select |>
  linpred_draws(
    newdata    = nd_spp_lss,
    dpar       = "hu",
    re_formula = NA
  ) %>%
  ungroup()

```

# look at distributions before cuttoffs
```{r}

co_summary = brms_data %>%
  group_by(taxon_capture) %>%
  summarize(n = n(),
            p_neg = sum(bd_its_copies == 0) / n(),
            p_10 = sum(bd_its_copies > 0 & bd_its_copies < 10) / n(),
            p_pos = sum(bd_its_copies > 10) / n(),
            med_pos = median(bd_its_copies[bd_its_copies > 0]),
            max = max(bd_its_copies))

ggplot(brms_data, aes(x = bd_its_copies)) +
  geom_density() +
  facet_wrap("taxon_capture") +
  xlim(0, 20)

```

# look at heteroscedasticity
```{r}
# compute per-population mean and SD of log-load
# if mean and SD are uncorrelated, sigma variation is independent of mean variation
brms_data |>
  filter(bd_load_co_density > 0) |>
  group_by(taxon_capture, population) |>
  summarise(
    n        = n(),
    mean_log = mean(log(bd_load_co_density)),
    sd_log   = sd(log(bd_load_co_density)),
    .groups  = "drop"
  ) |>
  filter(n >= 5) |>
  ggplot(aes(x = mean_log, y = sd_log)) +
  geom_point(aes(size = n), alpha = 0.5) +
  geom_smooth(method = "lm") +
  facet_wrap("taxon_capture", scales = "free") +
  labs(x = "Population mean log-load",
       y = "Population SD log-load",
       title = "Mean vs spread of log-load by population within taxon") +
  theme_minimal()

```

# look at within-taxa variation in population-level SD
```{r}
peace = brms_data |>
  filter(bd_load_co_density > 0) |>
  group_by(taxon_capture, population) |>
  summarise(
    sd_log   = sd(log(bd_load_co_density)),
    n        = n(),
    .groups  = "drop"
  ) |>
  filter(n >= 5) |>
  group_by(taxon_capture) |>
  summarise(
    between_pop_cv = sd(sd_log) / mean(sd_log),  # how much does sigma vary across pops within taxon
    .groups = "drop"
  ) |>
  arrange(desc(between_pop_cv))

```