---
title: "species_natural_hx"
format: html
---

```{r}
librarian::shelf(tidyverse, here, iucnredlist, rio, janitor)

load(here("size_bd_unified", "intermediates", "bd_model_env_unified_2026-04-03.RData"))

species_list = brms_data %>%
  select(taxon_capture) %>%
  distinct() %>%
  mutate(sn = str_to_sentence(gsub("_", " ", taxon_capture)),
         sn = recode_values(taxon_capture,
                               "hyla_cinerea" ~ "Dryophytes cinereus",
                               "hyla_versicolor" ~ "Dryophytes versicolor",
                               "rana_catesbeiana" ~ "Aquarana catesbeianus",
                               "rana_clamitans" ~ "Aquarana clamitans",
                               "rana_pipiens" ~ "Lithobates pipiens",
                               "rana_sylvatica" ~ "Lithobates sylvaticus",
                            default = sn
         ),
         genus = str_split_fixed(sn, " ", 2)[,1],
         species = str_split_fixed(sn, " ", 2)[,2]) %>%
  arrange(sn)


```

# query iucn
```{r}
api = init_api(Sys.getenv("iucn_token"))

iucn_assessment = assessments_by_name(api, genus = species_list$genus[1], species = species_list$species[1]) %>%
    mutate(genus_q = species_list$genus[1],
           species_q = species_list$species[1]) %>%
    filter(FALSE) %>%
    select(genus_q,
           species_q,
           everything())

cat("\tLooking up species IDs\n")
  pb = txtProgressBar(min = 1, max = nrow(species_list), style = 3)
  for (ii in 1:nrow(species_list)) {
    ii_genus = species_list$genus[ii]
    ii_species = species_list$species[ii]
    setTxtProgressBar(pb, ii)

    # pull data
    new_row <- tryCatch({
      assessments_by_name(api, genus = ii_genus, species = ii_species) %>%
        mutate(genus_q = ii_genus,
               species_q = ii_species) %>%
        slice_max(order_by = year_published, n = 1)
    }, error = function(e) {
      # fail silently
      NULL
    })

    # bind
    if (!is.null(new_row) && nrow(new_row) > 0) {
      iucn_assessment = bind_rows(iucn_assessment, new_row)
    }
    # sleep to avoid rate limiting
    Sys.sleep(0.5)
  }
  close(pb)
  
  
iucn_assessment_clean = iucn_assessment %>%
  distinct()

species_missing = species_list %>%
  anti_join(iucn_assessment_clean, by = c("genus" = "genus_q", "species" = "species_q"))
# fetch assessment data
cat("\tQuerying local taxa occurences\n")
iucn_assessment_data = assessment_data_many(api,
                                            iucn_assessment_clean$assessment_id,
                                            wait_time = 0.5)

habitats = tibble()
for (ii in 1:nrow(iucn_assessment_clean)) {
  temp = iucn_assessment_data[[ii]]$habitats %>%
    mutate(genus_q = iucn_assessment_clean$genus_q[ii],
           species_q = iucn_assessment_clean$species_q[ii],
           pop_trend = iucn_assessment_data[[ii]]$population_trend$description[1],
           redlist_category = iucn_assessment_data[[ii]]$red_list_category$description[1],
           redlist_code = iucn_assessment_data[[ii]]$red_list_category$code[1])
  
  habitats = bind_rows(habitats,
                       temp)
}

habitats_clean = habitats %>%
  select(genus_q,
         species_q,
         redlist_code,
         everything()) %>%
  mutate(code_base = as.integer(gsub("_\\d+", "", code))) %>%
  filter(suitability == "Suitable",
         code_base <= 13) %>%
  mutate(aquatic = (code_base %in% c(5))) %>%
  arrange(genus_q,
          species_q,
          code)

habitats_agg = habitats_clean %>%
  group_by(genus_q,
           species_q) %>%
  summarize(habitat_breadth = n(),
            aquatic_index = sum(aquatic) / n(),
            .groups = "drop") %>%
  right_join(species_list, by = c("species_q" = "species", "genus_q" = "genus")) %>%
  select(taxon_capture,
         habitat_breadth,
         aquatic_index)


write_csv(habitats_agg, here("size_bd_unified", "intermediates", "iucn_habitat_metrics.csv"))

```

# query Greenberg et al. 2017
```{r}
gb_data = import_list(here("data", "doi_10_5061_dryad_t54h6__v20170724", "Greenberg_Evol_Appl_full_dataset.xls"))
gb_full = gb_data[[1]] %>%
  clean_names()
gb_raw = gb_data[[2]] %>%
  clean_names()

gb_aligned = species_list %>%
  left_join(gb_raw, by = c("genus", "species")) %>%
  select(genus,
         species,
         ageat_maturity_yrs,
         source_28)
```