---
title: "05_species_meta_regression"
format: html
---

# Setup
```{r}
#| eval: true
#| output: false
#| code-fold: true
#| code-summary: "Show setup code"

# setup
librarian::shelf(tidyverse, here, brms, tidybayes, cmdstanr, emmeans)

```

# Load models and data
```{r}
# load models
null_zln = readRDS(file = here("size_bd_unified/unified_models/unified_model_results_zln_null.rds"))
m5g_zln = readRDS(file = "unified_models/unified_model_results_zln_life_tax_poptls2env2_30.rds")

model_select = m5g_zln

# emmeans specs
load(here("size_bd_unified", "intermediates", "bd_model_unified_bspecs_2026-03-22.RData"))
load(here("size_bd_unified", "intermediates", "bd_model_unified_bspecs_ls_2026-03-22.RData"))
load(here("size_bd_unified", "intermediates", "bd_model_unified_huspecs_2026-03-22.RData"))
load(here("size_bd_unified", "intermediates", "bd_model_unified_huspecs_ls_2026-03-22.RData"))
load(here("size_bd_unified", "intermediates", "bd_model_unified_sigmaspecs_2026-03-22.RData"))

# descriptive stats
load(here("data", "bd_model_env_unified_2026-03-22.RData"))

descriptive_stats = brms_data %>%
  group_by(taxon_capture) %>%
  summarize(max_svl_mm = max(svl_mm),
            .groups = "drop")

# phylogenetic covariance matrix
phylo_covar = readRDS(here("size_bd_unified", "intermediates", "phylo_covar.rds"))

# natural history traits
nhx = read_csv(here("data", "species_notes_2026-03-26.csv")) %>%
  clean_names() %>%
  mutate(pop_trend_present = factor(pop_trend_present,
                                    levels = c("decreasing", "stable", "increasing", "unknown"), 
                                    ordered = TRUE),
         iucn_redlist_category = factor(iucn_redlist_category,
                                    levels = c("LC-1", "LC", "VU", "EN", "CR"), 
                                    ordered = TRUE),
         development_stage = as.factor(development_stage)) %>%
  select(taxon_capture,
         pop_trend_present,
         iucn_redlist_category,
         development_stage)

# climate descriptors..,
## climate normals? or can I use the climate response models here?

```

# combine data
```{r}
hu_draws = hu_specs %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu = .value) %>%
  mutate(metric = "hu")

hu_contrasts_specs = contrast(hu_specs_ls, method = "revpairwise")

hu_contrast_draws = hu_contrasts_specs %>%
  gather_emmeans_draws() %>%
  dplyr::rename(hu_subadult = .value) %>%
  ungroup() %>%
  mutate(metric = "contrast_hu")

b_draws = b_specs %>%
  gather_emmeans_draws() %>%
  dplyr::rename(b = .value) %>%
  mutate(metric = "load")

b_contrasts_specs = contrast(b_specs_ls, method = "revpairwise")

b_contrast_draws = b_contrasts_specs %>%
  gather_emmeans_draws() %>%
  dplyr::rename(b_subadult = .value) %>%
  ungroup() %>%
  mutate(metric = "contrast_load")

sigma_draws = sigma_specs %>%
  gather_emmeans_draws() %>%
  dplyr::rename(sigma = .value) %>%
  mutate(metric = "sigma")

meta_data <- hu_draws |>
  select(taxon_capture, .draw, hu) |>
  left_join(
    hu_contrast_draws |> select(taxon_capture, .draw, hu_subadult),
    by = c("taxon_capture", ".draw")
  ) |>
  left_join(
    b_draws |> select(taxon_capture, .draw, b),
    by = c("taxon_capture", ".draw")
  ) |>
  left_join(
    b_contrast_draws |> select(taxon_capture, .draw, b_subadult),
    by = c("taxon_capture", ".draw")
  ) |>
  left_join(
    sigma_draws |> select(taxon_capture, .draw, sigma),
    by = c("taxon_capture", ".draw")
  )

meta_summary <- meta_data |>
  group_by(taxon_capture) |>
  summarise(
    across(c(hu, hu_subadult, b_subadult, sigma),
           list(mean = mean, sd = sd),
           .names = "{.col}_{.fn}")
  ) |>
  left_join(descriptive_stats, by = "taxon_capture") |>
  left_join(nhx, by = "taxon_capture")

```

# Model
```{r}
set_cmdstan_path(Sys.getenv("cmd_stan_path"))

fit_mv <- brm(
  mvbf(
    hu_mean      | mi(hu_sd)          ~ max_svl_mm + pop_trend_present + iucn_redlist_category + development_stage + (1 | p | gr(taxon_capture, cov = A)),
    hu_subadult_mean | mi(hu_subadult_sd) ~ max_svl_mm + pop_trend_present + iucn_redlist_category + development_stage + (1 | p | gr(taxon_capture, cov = A)),
    b_subadult_mean  | mi(b_subadult_sd)  ~ max_svl_mm + pop_trend_present + iucn_redlist_category + development_stage + (1 | p | gr(taxon_capture, cov = A)),
    sigma_mean   | mi(sigma_sd)       ~ max_svl_mm + pop_trend_present + iucn_redlist_category + development_stage + (1 | p | gr(taxon_capture, cov = A))
  ),
  data  = meta_summary,
  data2 = list(A = phylo_covar),
  # control = list(adapt_delta = 0.99, max_treedepth = 15),
  chains = 4,
  iter = 4000,
  warmup = 2000,
  seed = 124,
  cores = 4,
  backend = "cmdstanr"
)

fit_mv <- add_criterion(fit_mv, "loo")

saveRDS(fit_mv, file = here("size_bd_unified/unified_models/meta_model_mv.rds"))
fit_mv = readRDS(file = here("size_bd_unified/unified_models/meta_model_mv.rds"))

```

# model evaluation
```{r}
model_select = fit_mv
summary(model_select)
plot((model_select), ask = FALSE)
plot(conditional_effects(model_select), ask = FALSE)

```

# visualize
```{r}
fit_mv %>%
  gather_draws(`b_.*`, regex = TRUE) %>%
  filter(!grepl("Intercept", .variable)) %>%
  separate(.variable, into = c("prefix", "response", "term"),
           sep = "_", extra = "merge") %>%
  ggplot(aes(x = .value, y = term, color = response, fill = response)) +
  stat_halfeye(alpha = 0.6, .width = c(0.5, 0.89)) +
  geom_vline(xintercept = 0, linetype = "dashed") +
  facet_wrap(~ response, scales = "free_x") +
  theme_classic() +
  labs(x = "Posterior estimate", y = NULL,
       title = "Fixed effects across responses")
```

# explore specific groups
```{r}
# Example: IUCN category effect on hu_mean
iucn_grid <- expand_grid(
    iucn_redlist_category = unique(meta_summary$iucn_redlist_category),
    development_stage     = "larval",          # hold constant
    pop_trend_present     = "stable",                # hold at reference
    max_svl_mm            = median(meta_summary$max_svl_mm)
  ) %>%
  mutate(
    hu_sd             = 0.01,
    hu_subadult_sd    = 0.01,
    b_subadult_sd     = 0.01,
    sigma_sd          = 0.01
  )

# re_formula = NA marginalizes over phylogenetic RE
iucn_draws <- iucn_grid %>%
  add_epred_draws(fit_mv,
                  re_formula = NA,
                  resp = "husubadultmean")

iucn_draws %>%
  group_by(iucn_redlist_category) %>%
  median_qi(.epred, .width = c(0.5, 0.89)) %>%
  ggplot(aes(x = iucn_redlist_category, y = .epred,
             ymin = .lower, ymax = .upper)) +
  geom_pointrange() +
  theme_classic()


```